CREATE USER webserver IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO webserver;

CREATE USER kh IDENTIFIED BY kh;
GRANT CONNECT, RESOURCE TO kh;

---------------------------------------
CREATE USER examuser IDENTIFIED BY 1234;


GRANT CONNECT,RESOURCE TO examuser;

CREATE TABLE MEMBER_TBL(
MEMBER_ID VARCHAR2(30) PRIMARY KEY,
MEMBER_PW VARCHAR2(30) NOT NULL,
MEMBER_NAME VARCHAR2(20) NOT NULL
);