select * from chellenge_list;
select * from chellengeinfo;
select * from member_tbl;



INSERT INTO chellenge_list VALUES
(CHELLENGE_SEQ.NEXTVAL,
'지역:쓰담부산/상세지역:해운대/소요시간:10분 ~ 30분',
15,5,3,8,7,5,45,
'2022-09-27','망나니같은놈2.jpg',
21,
'Y','안녕하세요'
);

--회원번호 별로 GROUP BY 후, 총점수에 따라서 ORDER BY 하고 각각의 순위를 RANK로 띄움(승인된거만 1~5위까지)
SELECT rownum AS RANK, p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    MEMBER_NO
    FROM chellenge_list WHERE PERMISSION='Y' GROUP BY MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5;

(SELECT MEMBER_NO , MEMBER_ID, MEMBER_NAME, NICKNAME FROM MEMBER_TBL);

SELECT X.*, Y.* FROM (SELECT rownum AS RANK, p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    MEMBER_NO
    FROM chellenge_list WHERE PERMISSION='Y' GROUP BY MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5)X INNER JOIN (SELECT MEMBER_NO, MEMBER_ID 아이디, MEMBER_NAME 이름, NICKNAME 닉네임, MEMBER_INTRO 자기소개 FROM MEMBER_TBL)Y ON X.MEMBER_NO = Y.MEMBER_NO;

select * from chellenge_list;
select * from chellengeinfo;
select * from member_tbl;
commit;

--승인된 캔 유리 플라스틱 종이 등등 각각 모아놓은 쿼리문
SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 유리,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수
    FROM chellenge_list WHERE PERMISSION='Y';
    
    select * from member_tbl where member_id='kks111' and member_pw='User@111';
    
select x.*, y.* from 
(select * from member_tbl where member_id='admin' and member_pw='1234')x
inner join 
(SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 유리,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 점수,
    MEMBER_NO 
    FROM chellenge_list WHERE PERMISSION='Y' GROUP BY MEMBER_NO)y
    ON X.MEMBER_NO = Y.MEMBER_NO;

SELECT X.*, Y.* FROM (SELECT rownum AS RANK, p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    MEMBER_NO
    FROM chellenge_list WHERE PERMISSION='Y' GROUP BY MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5)X INNER JOIN (SELECT MEMBER_NO, MEMBER_ID 아이디, MEMBER_NAME 이름, NICKNAME 닉네임, MEMBER_INTRO 자기소개 FROM MEMBER_TBL)Y ON X.MEMBER_NO = Y.MEMBER_NO;
    
    
 select v.as path,b.* from(select member_no,max(photo_path) keep(dense_rank last order by quest_date) as path from chellenge_list  WHERE PERMISSION='Y' group by member_no)v right join (SELECT X.*, Y.* FROM (SELECT rownum AS RANK, p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    MEMBER_NO 
    FROM chellenge_list WHERE PERMISSION='Y' GROUP BY MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5)X inner JOIN (SELECT MEMBER_NO, MEMBER_ID 아이디, MEMBER_NAME 이름, NICKNAME 닉네임, MEMBER_INTRO 자기소개 FROM MEMBER_TBL)Y ON X.MEMBER_NO = Y.MEMBER_NO)b on  v.member_no = b.member_no;
    
    select member_no 하이 ,max(photo_path) keep(dense_rank last order by quest_date) PHOTO from chellenge_list WHERE PERMISSION='Y' group by member_no;
    SELECT X.*, Y.* FROM (SELECT p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    MEMBER_NO 
    FROM chellenge_list WHERE PERMISSION='Y' GROUP BY MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5)X INNER JOIN (SELECT MEMBER_NO, MEMBER_ID 아이디, MEMBER_NAME 이름, NICKNAME 닉네임, MEMBER_INTRO 자기소개 FROM MEMBER_TBL)Y ON X.MEMBER_NO = Y.MEMBER_NO;
    
    
    
    
    select member_no 하이 ,max(photo_path) keep(dense_rank last order by quest_date) PHOTO from chellenge_list WHERE PERMISSION='Y' group by member_no;
    
    UPDATE CHELLENGE_LIST SET PERMISSION='Y' WHERE QUEST_NO='26';
    
    COMMIT;
    
    SELECT * FROM chellenge_list;
    SELECT QUEST_NO,MEMBER_NO,PHOTO_PATH FROM CHELLENGE_LIST WHERE PERMISSION='Y';
    SELECT MAX(QUEST_NO) AS QUEST_MAX,MEMBER_NO FROM CHELLENGE_LIST WHERE PERMISSION='Y' GROUP BY MEMBER_NO;
    
    SELECT E.MEMBER_NO, M.PHOTO_PATH FROM (SELECT MAX(QUEST_NO) AS QUEST_MAX,MEMBER_NO FROM CHELLENGE_LIST CL2 WHERE PERMISSION='Y' GROUP BY CL2.MEMBER_NO)E INNER JOIN (SELECT QUEST_NO,CL.MEMBER_NO,PHOTO_PATH FROM CHELLENGE_LIST CL WHERE PERMISSION='Y')M ON E.QUEST_MAX =M.QUEST_NO;

    SELECT L.*,O.PHOTO_PATH FROM 
    (SELECT X.*, Y.* FROM (SELECT rownum AS RANK, p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    CL3.MEMBER_NO
    FROM chellenge_list CL3 WHERE PERMISSION='Y' GROUP BY CL3.MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5)X INNER JOIN (SELECT M.MEMBER_NO, MEMBER_ID 아이디, MEMBER_NAME 이름, NICKNAME 닉네임, MEMBER_INTRO 자기소개 FROM MEMBER_TBL M)Y ON X.MEMBER_NO = Y.MEMBER_NO)L 
    INNER JOIN
    (SELECT E.MEMBER_NO, M.PHOTO_PATH FROM (SELECT MAX(QUEST_NO) AS QUEST_MAX,MEMBER_NO FROM CHELLENGE_LIST CL2 WHERE PERMISSION='Y' GROUP BY CL2.MEMBER_NO)E INNER JOIN (SELECT QUEST_NO,CL.MEMBER_NO,PHOTO_PATH FROM CHELLENGE_LIST CL WHERE PERMISSION='Y')M ON E.QUEST_MAX =M.QUEST_NO)O 
    ON L.MEMBER_NO=O.MEMBER_NO;


    SELECT X.*, Y.* FROM (SELECT rownum AS RANK, p.* FROM (SELECT * FROM (SELECT n.* FROM (SELECT SUM(QUEST_CAN) 캔,
    SUM(QUEST_PLA) 플라스틱,
    SUM(QUEST_GLASS) 병,
    SUM(QUEST_PAPER) 종이,
    SUM(QUEST_WRAPPER) 비닐,
    SUM(QUEST_TABACOO) 담배꽁초,
    SUM(QUEST_POINT) 총점수,
    MEMBER_NO,
    (SELECT PHOTO_PATH FROM CHELLENGE_LIST WHERE QUEST_NO IN (SELECT MAX(QUEST_NO) AS QUEST_MAX FROM CHELLENGE_LIST CL2 WHERE PERMISSION='Y' AND CL2.MEMBER_NO = CL.MEMBER_NO)) AS PHOTO_PATH
    FROM chellenge_list CL WHERE PERMISSION='Y' GROUP BY MEMBER_NO)n) ORDER BY 총점수 DESC)p WHERE ROWNUM BETWEEN 1 AND 5)X INNER JOIN (SELECT M.MEMBER_NO, MEMBER_ID 아이디, MEMBER_NAME 이름, NICKNAME 닉네임, MEMBER_INTRO 자기소개 FROM MEMBER_TBL M)Y ON X.MEMBER_NO = Y.MEMBER_NO;
    
    
    
    (SELECT PHOTO_PATH,MEMBER_NO FROM CHELLENGE_LIST WHERE QUEST_NO IN (SELECT MAX(QUEST_NO) AS QUEST_MAX FROM CHELLENGE_LIST CL2 WHERE PERMISSION='Y' GROUP BY MEMBER_NO));
    
    SELECT * FROM chellenge_list;
    SELECT * FROM MEMBER_TBL;
    
    SELECT * FROM CREW_TBL;
    select * from member_tbl;
    INSERT INTO CREW_TBL VALUES(CREW_SEQ.NEXTVAL,?,?,?,?,?,?,?);
    
