/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-27 03:05:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chellenge;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.earthpurging.member.model.vo.Member;

public final class quest2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.earthpurging.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String city = (String)request.getAttribute("cityName");
	Member member = (Member)session.getAttribute("m");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>쓰담step1</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/quest2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write(" <script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  .sub_btn {\r\n");
      out.write("  background: url(/img/img/address.png) no-repeat center center;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  width: 126px;\r\n");
      out.write("  height: 37px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  background-size: contain;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  .flag_title::before {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 18px;\r\n");
      out.write("  height: 29px;\r\n");
      out.write("  background: url(/img/flag.png) no-repeat center center;\r\n");
      out.write("  background-size: 18px 29px;\r\n");
      out.write("  left: -35px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("}\r\n");
      out.write(".stepBth{\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-family: DungGeunMo;\r\n");
      out.write("}\r\n");
      out.write(".button_su_inner{\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"quick\">\r\n");
      out.write("    <a class=\"kakao_btn\" href=\"http://pf.kakao.com/_HxcUhb\" target=\"_blank\"><img src=\"/img/img/kakao.png\" alt=\"카카오톡\"></a>\r\n");
      out.write("    <div class=\"top_btn1\"><a href=\"/\"><img src=\"/img/img/plog_logo.png\" class=\"plog_logo\"></a></div>\r\n");
      out.write("    <div class=\"top_btn\"><p>↑<br>TOP</p></div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div id=\"step\">\r\n");
      out.write("      <div class=\"sub_wrapper\">\r\n");
      out.write("        <div class=\"top_title\">\r\n");
      out.write("          <div class=\"border2\">\r\n");
      out.write("            <div class=\"border3\">\r\n");
      out.write("              <div class=\"top\">\r\n");
      out.write("                <img src=\"/img/img/bumb_left.gif\" alt=\"폭탄\" class=\"bumb1\">\r\n");
      out.write("                <h5>STEP 01</h5>\r\n");
      out.write("                <img src=\"/img/img/bumb_right.gif\" alt=\"폭탄\" class=\"bumb2\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"bt\">\r\n");
      out.write("                <img src=\"/img/img/sub_title.png\" alt=\"쓰담기록\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- form <!--  -->\r\n");
      out.write("      <form id=\"inqForm\" name=\"inqForm\" method=\"post\" action=\"/quest3.do\" enctype=\"multipart/form-data\">\r\n");
      out.write("          <input type=\"hidden\" name=\"step\" value=\"1\">\r\n");
      out.write("           <input type=\"hidden\" name=\"memberNO\" value=\"");
      out.print(member.getMemberNo());
      out.write("\">\r\n");
      out.write("        <div class=\"form_wrap\">   \r\n");
      out.write("          <div class=\"form_title ffff\">\r\n");
      out.write("            이렇게 <span class=\"yellow\">줍<img src=\"/img/img/star.png\" alt=\"별\">줍</span>했다!\r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("          <div class=\"form_box\">\r\n");
      out.write("            <div class=\"flag_title\">\r\n");
      out.write("              <p class=\"org\">줍줍 일자</p>\r\n");
      out.write("              <p class=\"shadow\">줍줍 일자</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"input-daterange input-group\" id=\"flight-datepicker\">\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <input class=\"input-sm form-control input_grey\" type=\"text\" id=\"start-date\" name=\"p_start\" placeholder=\"쓰담한 날짜를 선택해 주세요.\"autocomplete=\"OFF\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("          <div class=\"form_box\">\r\n");
      out.write("            <div class=\"flag_title\">\r\n");
      out.write("              <p class=\"org\">줍줍한 위치</p>\r\n");
      out.write("              <p class=\"shadow\">줍줍한 위치</p>\r\n");
      out.write("            </div>\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"form_cont\">\r\n");
      out.write("            ");
if (city.equals("쓰담강릉")){ 
      out.write("\r\n");
      out.write("             <select name=\"p_city\" id=\"p_city\" class=\"input_grey\">\r\n");
      out.write("                <option value=\"쓰담강릉\" selected>쓰담강릉</option>\r\n");
      out.write("                <option value=\"쓰담전주\" >쓰담전주</option>\r\n");
      out.write("                <option value=\"쓰담부산\" >쓰담부산</option>\r\n");
      out.write("                <option value=\"쓰담제주\" >쓰담제주</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            ");
} else if(city.equals("쓰담전주")) { 
      out.write("\r\n");
      out.write("               <select name=\"p_city\" id=\"p_city\" class=\"input_grey\">\r\n");
      out.write("                <option value=\"쓰담강릉\" >쓰담강릉</option>\r\n");
      out.write("                <option value=\"쓰담전주\" selected>쓰담전주</option>\r\n");
      out.write("                <option value=\"쓰담부산\" >쓰담부산</option>\r\n");
      out.write("                <option value=\"쓰담제주\" >쓰담제주</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            ");
} else if(city.equals("쓰담부산")) {
      out.write("\r\n");
      out.write("             <select name=\"p_city\" id=\"p_city\" class=\"input_grey\">\r\n");
      out.write("                <option value=\"쓰담강릉\" >쓰담강릉</option>\r\n");
      out.write("                <option value=\"쓰담전주\" >쓰담전주</option>\r\n");
      out.write("                <option value=\"쓰담부산\" selected>쓰담부산</option>\r\n");
      out.write("                <option value=\"쓰담제주\" >쓰담제주</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            ");
} else if(city.equals("쓰담제주")) {
      out.write("\r\n");
      out.write("             <select name=\"p_city\" id=\"p_city\" class=\"input_grey\">\r\n");
      out.write("                <option value=\"쓰담강릉\" >쓰담강릉</option>\r\n");
      out.write("                <option value=\"쓰담전주\" >쓰담전주</option>\r\n");
      out.write("                <option value=\"쓰담부산\" >쓰담부산</option>\r\n");
      out.write("                <option value=\"쓰담제주\" selected >쓰담제주</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            ");
} else{
      out.write("\r\n");
      out.write("             <select name=\"p_city\" id=\"p_city\" class=\"input_grey\">\r\n");
      out.write("                <option value=\"쓰담강릉\" >쓰담강릉</option>\r\n");
      out.write("                <option value=\"쓰담전주\" >쓰담전주</option>\r\n");
      out.write("                <option value=\"쓰담부산\" >쓰담부산</option>\r\n");
      out.write("                <option value=\"쓰담제주\"  >쓰담제주</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("             \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"flex address_flex\">\r\n");
      out.write("              <div>쓰레기 데이터 수집을 위해 대략적 위치를 표기해주세요. <br>애매한 경우, 가장 가까운 랜드마크나 건물을 입력해주세요.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <textarea id=\"p_addr\" name=\"p_addr\" class=\"input_grey h100\"></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("          <div class=\"form_box\">\r\n");
      out.write("            <div class=\"flag_title\">\r\n");
      out.write("              <p class=\"org\">득템 리스트</p>\r\n");
      out.write("              <p class=\"shadow\">득템 리스트</p>\r\n");
      out.write("            </div>\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"form_cont flex\">\r\n");
      out.write("              <div class=\"get_item\">\r\n");
      out.write("                <img src=\"/img/img/icon2.png\" alt=\"득템리스트\">\r\n");
      out.write("                <div class=\"fff\">캔류(3점)</div>\r\n");
      out.write("                <div class=\"count_input\">\r\n");
      out.write("                  <span class=\"minus\">-</span>\r\n");
      out.write("                  <input type=\"text\" value=\"0\" id='p_item_1 ip' name='p_item_1' class=\"input_grey\" onKeyup=\"this.value=this.value.replace(/[^-0-9]/g,'');\">\r\n");
      out.write("                  <span class=\"plus\">+</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"get_item\">\r\n");
      out.write("                <img src=\"/img/img/icon7.png\" alt=\"득템리스트\">\r\n");
      out.write("                <div class=\"fff\">유리류(3점)</div>\r\n");
      out.write("                <div class=\"count_input\">\r\n");
      out.write("                  <span class=\"minus\">-</span>\r\n");
      out.write("                  <input type=\"text\" value=\"0\" id='p_item_2 ip' name='p_item_2' class=\"input_grey\" onKeyup=\"this.value=this.value.replace(/[^-0-9]/g,'');\">\r\n");
      out.write("                  <span class=\"plus\">+</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"get_item\">\r\n");
      out.write("                <img src=\"/img/img/icon1.png\" alt=\"득템리스트\">\r\n");
      out.write("                <div class=\"fff\">종이류(2점)</div>\r\n");
      out.write("                <div class=\"count_input\">\r\n");
      out.write("                  <span class=\"minus\">-</span>\r\n");
      out.write("                  <input type=\"text\" value=\"0\" id='p_item_3 ip' name='p_item_3'  class=\"input_grey\" onKeyup=\"this.value=this.value.replace(/[^-0-9]/g,'');\">\r\n");
      out.write("                  <span class=\"plus\">+</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"get_item\">\r\n");
      out.write("                <img src=\"/img/img/icon4.png\" alt=\"득템리스트\">\r\n");
      out.write("                <div class=\"fff\">플라스틱류(2점)</div>\r\n");
      out.write("                <div class=\"count_input\">\r\n");
      out.write("                  <span class=\"minus\">-</span>\r\n");
      out.write("                  <input type=\"text\" value=\"0\" id='p_item_4 ip' name='p_item_4' class=\"input_grey\" onKeyup=\"this.value=this.value.replace(/[^-0-9]/g,'');\">\r\n");
      out.write("                  <span class=\"plus\">+</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"get_item\">\r\n");
      out.write("                <img src=\"/img/img/icon9.png\" alt=\"득템리스트\">\r\n");
      out.write("                <div class=\"fff\">담배꽁초류(1점)</div>\r\n");
      out.write("                <div class=\"count_input\">\r\n");
      out.write("                  <span class=\"minus\">-</span>\r\n");
      out.write("                  <input type=\"text\" value=\"0\" id='p_item_5 ip' name='p_item_5' class=\"input_grey\" onKeyup=\"this.value=this.value.replace(/[^-0-9]/g,'');\">\r\n");
      out.write("                  <span class=\"plus\">+</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"get_item\">\r\n");
      out.write("                <img src=\"/img/img/icon5.png\" alt=\"득템리스트\">\r\n");
      out.write("                <div class=\"fff\">비닐류(1점)</div>\r\n");
      out.write("                <div class=\"count_input\">\r\n");
      out.write("                  <span class=\"minus\">-</span>\r\n");
      out.write("                  <input type=\"text\"  id='p_item_6 ip' name='p_item_6' value=\"0\" class=\"input_grey\" onKeyup=\"this.value=this.value.replace(/[^-0-9]/g,'');\">\r\n");
      out.write("                  <span class=\"plus\">+</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("          <div class=\"form_box\">\r\n");
      out.write("            <div class=\"flag_title\">\r\n");
      out.write("              <p class=\"org\">소요시간</p>\r\n");
      out.write("              <p class=\"shadow\">소요시간</p>\r\n");
      out.write("            </div>\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"form_cont\">\r\n");
      out.write("              <select name=\"p_time\" id=\"p_time\" class=\"input_grey\">\r\n");
      out.write("                <option value=\"~ 10분 이하\">~ 10분 이하</option>\r\n");
      out.write("                <option value=\"10분 ~ 30분\">10분 ~ 30분</option>\r\n");
      out.write("                <option value=\"30분 ~ 1시간\">30분 ~ 1시간</option>\r\n");
      out.write("                <option value=\"1시간 ~ 2시간\">1시간 ~ 2시간</option>\r\n");
      out.write("                <option value=\"2시간 초과\">2시간 초과</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("          <div class=\"form_box align_base\">\r\n");
      out.write("            <div class=\"photo_file\">\r\n");
      out.write("              <div class=\"flag_title\">\r\n");
      out.write("                <div>\r\n");
      out.write("                  <p class=\"org\">이미지 업로드</p>\r\n");
      out.write("                  <p class=\"shadow\">이미지 업로드</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"form_cont m_bt flex1\">\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"lt\">\r\n");
      out.write("                  <div class=\"filebox filebox1\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <label for=\"ex_filename1\" class=\"sub_btn\">이동기록</label>\r\n");
      out.write("                      <input type=\"file\" id=\"ex_filename1\" name=\"p_file1\" class=\"upload-hidden\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"step\" value=\"1\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <textarea readonly class=\"upload-name upload-name1 input_grey h165\" placeholder=\"날짜, GPS지도, 이동거리가 담긴 캡쳐 이미지&#13;&#10;(1MByte 미만 권장)\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"rt\">\r\n");
      out.write("                  <div class=\"photo_img\">\r\n");
      out.write("                    <img src=\"/img/img/sub_photo2.png\" alt=\"예시이미지\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"form_cont flex1\">\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"lt\">\r\n");
      out.write("                  <div class=\"filebox filebox2\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <label for=\"ex_filename2\" class=\"sub_btn\">인증샷</label>\r\n");
      out.write("                      <input type=\"file\" id=\"ex_filename2\" name=\"p_file2\" class=\"upload-hidden\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <textarea readonly class=\"upload-name upload-name2 input_grey h165\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"rt\">\r\n");
      out.write("                  <div class=\"photo_img\">\r\n");
      out.write("                    <img src=\"/img/img/sub_photo1.png\" alt=\"예시이미지\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("          <div class=\"form_box\">\r\n");
      out.write("            <div class=\"flag_title\">\r\n");
      out.write("              <p class=\"org\">동료들에게 남길 퀘스트 수행 소감 한마디!</p>\r\n");
      out.write("              <p class=\"shadow\">동료들에게 남길 퀘스트 수행 소감 한마디!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"form_cont\">\r\n");
      out.write("              <textarea id='p_memo' name='p_memo' class=\"input_grey h100 review\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("          <div class=\"form_bt \">\r\n");
      out.write("            <div class=\"button_su\">\r\n");
      out.write("              <span class=\"su_button_circle\"></span>\r\n");
      out.write("              <div id=\"nextStep\" class=\"button_su_inner\">\r\n");
      out.write("                <button type=\"submit\" class=\"button_text_container nextBtn stepBth\">\r\n");
      out.write("                  <span>STEP 02로 <br>넘어가기</span><span class=\"yellow\">▶</span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--------------------------------------->\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("      </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"noto\">\r\n");
      out.write("    <div class=\"top1 fx\">\r\n");
      out.write("      <div class=\"borderR borderL\">\r\n");
      out.write("        <p class=\"txt\">지구 푸르깅</p>\r\n");
      out.write("        <p class=\"line\"></p>\r\n");
      out.write("        <p class=\"txt\">kh</p>\r\n");
      out.write("        <p class=\"line\"></p>\r\n");
      out.write("        <p class=\"txt\">202-82-02232</p>\r\n");
      out.write("        <p class=\"line mo_none\"></p>\r\n");
      out.write("        <p class=\"txt mo_b\">서울시 kh 정보교육원 19F</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"borderR\">\r\n");
      out.write("        <p class=\"txt\">kh@iei.or.kr</p>\r\n");
      out.write("        <p class=\"line mo_none\"></p>\r\n");
      out.write("        <p class=\"txt mo_b\">고객센터 <span class=\"mo_none\">전화번호</span> 02-2010-2300</p>\r\n");
      out.write("        <p class=\"line mo_none\"></p>\r\n");
      out.write("        <p class=\"txt mo_b\"><span class=\"mo_none\">고객센터 </span>팩스번호 02-225-4820</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"copy\">Copyright ⓒ 지구푸르깅 All rights reserved.</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/quest2.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
