/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-27 03:04:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chellenge;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.earthpurging.member.model.vo.Member;

public final class quest1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.earthpurging.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	Member member = (Member)session.getAttribute("m");
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>쓰담step1</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/quest1.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".game_wrap{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 0 0 15% 0;\r\n");
      out.write("    background-image: url(/img/img/game_top.png), url(/img/img/game_bt.gif);\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-position: top, bottom;\r\n");
      out.write("    background-size: contain;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 오른쪽 하단에 카톡/top/main가는 버튼 -->\r\n");
      out.write("	<div id=\"quick\">\r\n");
      out.write("		<a class=\"kakao_btn\" href=\"http://pf.kakao.com/_HxcUhb\"\r\n");
      out.write("			target=\"_blank\"><img src=\"/img/img/kakao.png\" alt=\"카카오톡\"></a>;\r\n");
      out.write("		<div class=\"top_btn1\">\r\n");
      out.write("			<a href=\"/\"><img src=\"/img/img/plog_logo.png\" class=\"plog_logo\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"top_btn\">\r\n");
      out.write("			<p>\r\n");
      out.write("				↑<br>TOP\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"main\" class=\"grid\">\r\n");
      out.write("		<section id=\"main_top\">\r\n");
      out.write("			<div class=\"wrapper\">\r\n");
      out.write("				<div class=\"logo_wrap\">\r\n");
      out.write("					<a href=\"#\" class=\"logoImg\"> <img src=\"/img/img/plog_logo.png\"\r\n");
      out.write("						alt=\"플로깅\" id=\"plogImg\">\r\n");
      out.write("					</a> <a href=\"#\" target=\"_blank\" class=\"logoImg\"> <span> <img\r\n");
      out.write("							src=\"/img/img/logo2.png\" alt=\"지구쓰담\" id=\"logoImg\">\r\n");
      out.write("					</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"titles center\">\r\n");
      out.write("					<div class=\"titleText\">힙한지구인 되기 대-작전!</div>\r\n");
      out.write("					<div class=\"main_title\">\r\n");
      out.write("						<div class=\"top_title\">\r\n");
      out.write("							<!-- 노랑 -->\r\n");
      out.write("							<img src=\"/img/img/top_title1.png\" alt=\"쓰담위크 퀘스트\"\r\n");
      out.write("								class=\"top_title1\">\r\n");
      out.write("							<!-- 핑크 -->\r\n");
      out.write("							<img src=\"/img/img/top_title2.png\" alt=\"쓰담위크 퀘스트\"\r\n");
      out.write("								class=\"top_title2\">\r\n");
      out.write("							<!-- 투명 -->\r\n");
      out.write("							<img src=\"/img/img/top_title3.png\" alt=\"쓰담위크 퀘스트\"\r\n");
      out.write("								class=\"top_title3\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"character_wrap\">\r\n");
      out.write("					<div class=\"character\">\r\n");
      out.write("						<img src=\"/img/img/character1.png\" alt=\"\">\r\n");
      out.write("						<p style=\"color: #fff;\">쓰담 도사</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"char-box\" style=\"color: #fff;\">\r\n");
      out.write("						<div class=\"char_textBox\">\r\n");
      out.write("							<img src=\"/img/img/chat_top.png\" class=\"chat_top\">\r\n");
      out.write("							<div class=\"char_text\">\r\n");
      out.write("								<div>\r\n");
      out.write("									용사여 반갑네! 방가방가 <br> <br> 그대는 깨끗하고 아름답던 지구별을 기억하는가? <br>(카운팅\r\n");
      out.write("									스타~ 밤하늘에 벼어얼) <br> <br> 지금은 쓰레기에 묻혀 그 빛을 잃은 지 오렌지.\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"highlight\">\r\n");
      out.write("									부디 지구를 뒤덮은 쓰레기를 주워담아 산과 강과 바다와 <br> 모든 거리가 본연의 모습으로 돌아올수\r\n");
      out.write("									있도록 도와주게.\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									혼자서는 어렵다고? 너무 걱정 말게나. (자넨 친구가 없나?) <br> 그대와 뜻을 함께할 동료들이 옆에\r\n");
      out.write("									있다네\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									여정을 마치고 돌아와 이야기를 들려주게. <br> 그럼 <span class=\"highlight\">[힙한\r\n");
      out.write("										지구인]의 훈장</span>을 그대에게 내리겠네!(뿜뿜뿜~!)\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/img/img/chat_bt.png\" class=\"chat_bottom\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- 쓰담위크 START -->\r\n");
      out.write("		<section id=\"sec1\">\r\n");
      out.write("			<div class=\"wrapper\">\r\n");
      out.write("				<div class=\"sec_title\">\r\n");
      out.write("					<img src=\"/img/img/title1.png\" alt=\"쓰담위크퀘스트\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"game_wrap\">\r\n");
      out.write("					<div class=\"game_top\">\r\n");
      out.write("						<img src=\"/img/img/game1.png\" class=\"game1\"> \r\n");
      out.write("						<img src=\"/img/img/heart.png\" class=\"game2\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"game_text\">\r\n");
      out.write("						어느 도시에서 <br> 퀘스트를 수행하시겠습니까? <br> 원하는 장소를 클릭하세요!\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"city_wrap\">\r\n");
      out.write("						<li><a href=\"/quest2Frm.do?city=쓰담강릉\">\r\n");
      out.write("								<div class=\"poly\">\r\n");
      out.write("									<img src=\"/img/img/game3.png\" alt=\"삼각형\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"city\">\r\n");
      out.write("									<p class=\"org\">쓰담강릉</p>\r\n");
      out.write("									<p class=\"white\">쓰담강릉</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"with\">\r\n");
      out.write("									<img src=\"/img/img/game2.png\" alt=\"용사\"> <span>x22</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"/quest2Frm.do?city=쓰담전주\">\r\n");
      out.write("								<div class=\"poly\">\r\n");
      out.write("									<img src=\"/img/img/game3.png\" alt=\"삼각형\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"city\">\r\n");
      out.write("									<p class=\"org\">쓰담전주</p>\r\n");
      out.write("									<p class=\"white\">쓰담전주</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"with\">\r\n");
      out.write("									<img src=\"/img/img/game2.png\" alt=\"용사\"> <span>x2</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"/quest2Frm.do?city=쓰담부산\">\r\n");
      out.write("								<div class=\"poly\">\r\n");
      out.write("									<img src=\"/img/img/game3.png\" alt=\"삼각형\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"city\">\r\n");
      out.write("									<p class=\"org\">쓰담부산</p>\r\n");
      out.write("									<p class=\"white\">쓰담부산</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"with\">\r\n");
      out.write("									<img src=\"/img/img/game2.png\" alt=\"용사\"> <span>x202</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"/quest2Frm.do?city=쓰담제주\">\r\n");
      out.write("								<div class=\"poly\">\r\n");
      out.write("									<img src=\"/img/img/game3.png\" alt=\"삼각형\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"city\">\r\n");
      out.write("									<p class=\"org\">쓰담제주</p>\r\n");
      out.write("									<p class=\"white\">쓰담제주</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"with\">\r\n");
      out.write("									<img src=\"/img/img/game2.png\" alt=\"용사\"> <span>x220</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"stop_wrap\">\r\n");
      out.write("					<img src=\"/img/img/stop.png\" class=\"stop\">\r\n");
      out.write("					<div class=\"character_wrap\">\r\n");
      out.write("						<div class=\"character\">\r\n");
      out.write("							<img src=\"/img/img/character2.png\">\r\n");
      out.write("							<p class=\"she\">쓰담이</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"char_text1\">\r\n");
      out.write("							<div class=\"chat_stroke\"></div>\r\n");
      out.write("							<div class=\"chat\">\r\n");
      out.write("								<img src=\"/img/img/chat_w_top.png\" class=\"textImg1\">\r\n");
      out.write("								<div class=\"chat_textBox cb\">\r\n");
      out.write("									안녕하세요! <br> 저는 여러분의 쓰담위크 퀘스트를 도와드릴 \"쓰담이\"예요. <br> 합한\r\n");
      out.write("									지구인이 되고 싶다면 제 설명을 천천히 따라와주세요!\r\n");
      out.write("								</div>\r\n");
      out.write("								<img src=\"/img/img/chat_w_bt.png\" class=\"textImg2\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- 지구쓰담 캠페인 -->\r\n");
      out.write("        <section id=\"sec2\">\r\n");
      out.write("            <div class=\"wrapper wrap_sec2\">\r\n");
      out.write("                <div class=\"sec_title\">\r\n");
      out.write("                    <img src=\"/img/img/title2.png\" alt=\"지구쓰담캠페인\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"character_wrap\">\r\n");
      out.write("                    <div class=\"character\">\r\n");
      out.write("                        <img src=\"/img/img/character2.png\">\r\n");
      out.write("                        <p class=\"she\">쓰담이</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"char_text2\">\r\n");
      out.write("                        <div class=\"chat_stroke\"></div>\r\n");
      out.write("                        <div class=\"chat\">\r\n");
      out.write("                            <img src=\"/img/img/chat_w_top.png\" class=\"textImg1\">\r\n");
      out.write("                            <div class=\"chat_textBox cb2\">\r\n");
      out.write("                                <div class=\"chat_div\">\r\n");
      out.write("                                    <span class=\"highlight\">\"지구의 쓰레기를 담다!\"</span>라는 뜻이 담겨있는\r\n");
      out.write("                                    지구쓰담 캠페인은 \r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    심각한 플라스틱 쓰레기 문제를 알리고, 넘쳐나는 해양 쓰레기로 몸살을 \r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    앓는 바다를 깨끗하게 하기 위한 환경재단의 국내 환경 회복 캠페인이에요.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"chat_div\">\r\n");
      out.write("                                    쉽게 사용되고 버려지는 쓰레기 육지에서 강으로, 그리고 바다로 흘러 들어간답니다.\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    미세 플라스틱으로 분해된 쓰레기는 물고기에게, 그리고 우리의 입속으로 다시 돌아오겠죠.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    지구에 남겨진 쓰레기, 이대로 정말 괜찮을까요...? \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"/img/img/chat_w_bt.png\" class=\"textImg2\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sec2_bg\">\r\n");
      out.write("                <a href=\"#\" target=\"_blank\" class=\"push_btn\">\r\n");
      out.write("                    <img src=\"/img/img/push.png\" alt=\"push 버튼\" class=\"push_ani\">\r\n");
      out.write("                    <img src=\"/img/img/push_btn1.png\" alt=\"push 버튼\" class=\"push_button\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"trash\">\r\n");
      out.write("                    <img src=\"/img/img/trash.png\" alt=\"쓰레기\" class=\"trash_img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"person\">\r\n");
      out.write("                    <img src=\"/img/img/character3.png\" alt=\"사람\" class=\"ps person1\">\r\n");
      out.write("                    <img src=\"/img/img/character4.png\" alt=\"사람\" class=\"ps person2\">\r\n");
      out.write("                    <img src=\"/img/img/balloon1.png\" class=\"mk mark1\">\r\n");
      out.write("                    <img src=\"/img/img/balloon1.png\" class=\"mk mark2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sec2_bgImg\">\r\n");
      out.write("                    <div class=\"sec2_top\">\r\n");
      out.write("                        <img src=\"/img/img/bg_sea_top.png\" class=\"sea_top\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sec2_bt\">\r\n");
      out.write("                        <img src=\"/img/img/bg_sea_bt.png\" class=\"sea_bt\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- 쓰담위크 -->\r\n");
      out.write("        <section id=\"sec3\">\r\n");
      out.write("            <div class=\"wrapper wrap_sec3\">\r\n");
      out.write("                <div class=\"sec_title\">\r\n");
      out.write("                    <img src=\"/img/img/title3.png\" alt=\"쓰담위크\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"character_wrap\">\r\n");
      out.write("                    <div class=\"character\">\r\n");
      out.write("                        <img src=\"/img/img/character2.png\">\r\n");
      out.write("                        <p class=\"she\">쓰담이</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"char_text2\">\r\n");
      out.write("                        <div class=\"chat_stroke\"></div>\r\n");
      out.write("                        <div class=\"chat\">\r\n");
      out.write("                            <img src=\"/img/img/chat_w_top.png\" class=\"textImg1\">\r\n");
      out.write("                            <div class=\"chat_textBox\">\r\n");
      out.write("                                <div class=\"chat_div\">헥헥... 담배꽁초와 플라스틱이 너무 많네요.</div>\r\n");
      out.write("                                <div class=\"chat_div\">\r\n");
      out.write("                                    여러분, 플로깅(Plogging)에 대해 아시나요?\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    스웨덴어의 줍다 'Plocka upp' + 영어의 달리기 'jogging'이 합쳐진 말인데요,\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <span class=\"highlight\">달리기를 하면서 동시에 쓰레기를 줍는 환경정화  활동</span>이랍니다.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"highlight\">'쓰담달리기'</span>라는 우리말로 바꿔서 사용하면 더 좋아요.\r\n");
      out.write("                                    <br>지구와 우리의 몸이 모두 건강해지는 쓰담달리기,\r\n");
      out.write("                                    <br>바로 여러분이 수행할 퀘스트예요!\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"/img/img/chat_w_bt.png\" class=\"textImg2\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sec3_bg\">\r\n");
      out.write("                <div class=\"person1\">\r\n");
      out.write("                    <img src=\"/img/img/character5.png\" alt=\"사람\" class=\"ps1 person3\">\r\n");
      out.write("                    <img src=\"/img/img/character6.png\" alt=\"사람\" class=\"ps1 person4\">\r\n");
      out.write("                    <img src=\"/img/img/balloon2.png\" class=\"mk mark3\">\r\n");
      out.write("                    <img src=\"/img/img/balloon2.png\" class=\"mk mark4\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sec3_bgImg\">\r\n");
      out.write("                    <div class=\"sec3_top\">\r\n");
      out.write("                        <img src=\"/img/img/bg_sky2.png\" class=\"sky_top\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sec3_bt\">\r\n");
      out.write("                        <img src=\"/img/img/bg_ground.png\" class=\"ground_bt\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>  \r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- 쓰담 어플 사용법 -->\r\n");
      out.write("        <section id=\"sec4\">\r\n");
      out.write("            <ul class=\"wrapper step\">\r\n");
      out.write("                <li class=\"step1\">\r\n");
      out.write("                    <div  class=\"flex1\">\r\n");
      out.write("                        <div class=\"step_left\">\r\n");
      out.write("                            <div class=\"step_num\">\r\n");
      out.write("                                <div class=\"yellow\" style=\"color: yellow;\" >step1</div>\r\n");
      out.write("                                <div class=\"title\" style=\"color: white;\"> 준비</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"step_img\">\r\n");
      out.write("                                <img src=\"/img/img/step1.png\">\r\n");
      out.write("                            </div>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"step_right\" style=\"color: white;\">\r\n");
      out.write("                            <p class=\"step_txt1 chat_div\">\r\n");
      out.write("                                1) 집 어딘가 오천오백개쯤 있는 에코백이나 봉투.\r\n");
      out.write("                                <br>\r\n");
      out.write("                                집게 혹은 다회용 장갑을 준비해주세요.\r\n");
      out.write("                                <br>    \r\n");
      out.write("                                쓰담달리기를 하면서 새로운 쓰레기는 만들지 않기로 약속!\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step_text2\">\r\n");
      out.write("                                2) 인증을 위한 어플리케이션 다운받기 <br>\r\n");
      out.write("                                (<span class=\"highlight\"> ①날짜 ②GPS 지도 ③이동거리</span>가 표기되는 어플)\r\n");
      out.write("                                <br>\r\n");
      out.write("                                ex) 나이키런 클럽, 런데이, 스트라바, 페이서 등\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <img src=\"/img/img/arrow.png\" class=\"arrow\">\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"step1\">\r\n");
      out.write("                    <div  class=\"flex1\">\r\n");
      out.write("                        <div class=\"step_left\">\r\n");
      out.write("                            <div class=\"step_num\">\r\n");
      out.write("                                <div class=\"yellow\" style=\"color: yellow;\">step2</div>\r\n");
      out.write("                                <div class=\"title\" style=\"color: white;\">쓰담 <br>달리기</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"step_img\">\r\n");
      out.write("                                <img src=\"/img/img/step2.png\">\r\n");
      out.write("                            </div>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"step_right\" style=\"color: white;\">\r\n");
      out.write("                            <p class=\"step_txt1 chat_div\">\r\n");
      out.write("                                1) 인증용 어플리케이션 실행하기\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step_text2 chat_div\">\r\n");
      out.write("                                2) 쓰담 달리기 시작 <br>\r\n");
      out.write("                                <span class=\"highlight\">*꿀팁: 모바일 기기를 이용하면 터치 방식을 사용해 <br> 쓰담기록을 실시간 입력할 수 있어요!</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step_text3\">\r\n");
      out.write("                                3) 인증샷 촬영하기\r\n");
      out.write("                                <br>\r\n");
      out.write("                                (주운 쓰레기와 본인의 모습이 보이도록 촬영!)\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <img src=\"/img/img/arrow.png\" class=\"arrow\"></li>\r\n");
      out.write("                <li class=\"step1 step33\">\r\n");
      out.write("                    <div  class=\"flex1\">\r\n");
      out.write("                        <div class=\"step_left\">\r\n");
      out.write("                            <div class=\"step_num\">\r\n");
      out.write("                                <div class=\"yellow\" style=\"color: yellow;\" >step3</div>\r\n");
      out.write("                                <div class=\"title\" style=\"color: white;\">쓰담<br>기록제출</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"step_img\">\r\n");
      out.write("                                <img src=\"/img/img/step3.png\">\r\n");
      out.write("                            </div>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"step_right\" style=\"color: white;\">\r\n");
      out.write("                            <p class=\"step_txt1 chat_div\">\r\n");
      out.write("                                [쓰담기록지 구성]\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step_text2 chat_div\">\r\n");
      out.write("                                ① 쓰담기록 (날짜, 위치, 쓰레기 종류별 개수, 소요시간, 인증샷 업로드)\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <span class=\"highlight\">총 2장의 이미지를 업로드 해주세요(어플 기록거리 캡쳐 + 인증샷)</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <div class=\"subImg chat_div\"> \r\n");
      out.write("                                <img src=\"/img/img/sub_photo2.png\" alt=\"지도\" class=\"subImg1\">\r\n");
      out.write("                                <div class=\"plus\">+</div>\r\n");
      out.write("                                <img src=\"/img/img/sub_photo1.png\" alt=\"인증샷\" class=\"subImg2\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                ②힙한지구인의 정보(이름, 연락처, 이메일, 주소)\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- 힙한 지구인의 훈장 -->\r\n");
      out.write("        <section id=\"sec5\">\r\n");
      out.write("            <div class=\"wrapper wrap_sec2\">\r\n");
      out.write("                <div class=\"sec_title\">\r\n");
      out.write("                    <img src=\"/img/img/title4.png\" alt=\"힙한지구인의훈장\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"character_wrap\">\r\n");
      out.write("                    <div class=\"character\">\r\n");
      out.write("                        <img src=\"/img/img/character1.png\">\r\n");
      out.write("                        <p class=\"she\">쓰담이</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"char_text2\">\r\n");
      out.write("                        <div class=\"chat_stroke\"></div>\r\n");
      out.write("                        <div class=\"chat\">\r\n");
      out.write("                            <img src=\"/img/img/chat_w_top.png\" class=\"textImg1\">\r\n");
      out.write("                            <div class=\"chat_textBox\">\r\n");
      out.write("                                <div class=\"chat_div\">\r\n");
      out.write("                                    힙한 지구인의 훈장은 지구별을 깨끗하게 만든 훌룡한 용사들에게 하사하는 <br> 한정판 선물이라네.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"chat_div\">\r\n");
      out.write("                                    깨끗하고 아름다운 도시의 모습과 힙한 지구인의 모습이 한땀 한땀 수 놓아진 <br>자수패치일세.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    각 도시별로 선착순 100명의 용사들에게만 특별히 주어지는 것이니  <br>자네도 어서 서두르게나!\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"/img/img/chat_w_bt.png\" class=\"textImg2\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"patch\">\r\n");
      out.write("                    <img src=\"/img/img/patch1.png\" >\r\n");
      out.write("                    <img src=\"/img/img/patch2.png\" >\r\n");
      out.write("                    <img src=\"/img/img/patch3.png\" >\r\n");
      out.write("                    <img src=\"/img/img/patch4.png\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>쓰담한 도시 자수패치 1개</p>\r\n");
      out.write("                <div class=\"plus1\">+</div>\r\n");
      out.write("                <div class=\"patch\">\r\n");
      out.write("                    <img src=\"/img/img/patch5.png\">\r\n");
      out.write("                    <img src=\"/img/img/patch6.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"highlight hig\">!!도시별 선착순 100인 한정!!</div>\r\n");
      out.write("                <div class=\"jeju\">\r\n");
      out.write("                    <div style=\"color: white;\" class=\"jeju_txt\">\r\n");
      out.write("                        쓰담제주는 <span class=\"highlight\">문화도시 제주</span>와 함께합니다.\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <span class=\"under\">제주한정</span>추가 리워드 이벤트가 \r\n");
      out.write("                        <br>\r\n");
      out.write("                        궁금하다면? 눌러보세요!\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"/\" class=\"jeju1\">\r\n");
      out.write("                        <div class=\"jejuImg bellWrapper\">\r\n");
      out.write("                            <img src=\"/img/img/jeju.png\" alt=\"돌하르방\" class=\"my-bell\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"jeju_click\">click!</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href= \"/quest2Frm.do?city=쓰담강릉\" class=\"run33\">\r\n");
      out.write("                    <div class=\"run_start\">\r\n");
      out.write("                        <img src=\"/img/img/push2.png\" class=\"run_img\">\r\n");
      out.write("                        <img src=\"/img/img/push_btn2.png\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"run_start_txt\">쓰담달리기 출발!</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer class=\"noto\">\r\n");
      out.write("        <div class=\"top\"></div>\r\n");
      out.write("        <div class=\"copy\"></div>\r\n");
      out.write("    </footer>\r\n");
      out.write("		\r\n");
      out.write("		<script src=\"/js/quest1.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
