/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-26 09:07:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.earthpurging.index.model.vo.ChellengeMemberData;
import com.earthpurging.member.model.vo.Member;

public final class FAQ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1664172377681L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663920910595L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.earthpurging.index.model.vo.ChellengeMemberData");
    _jspx_imports_classes.add("com.earthpurging.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" 	<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/news.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/FAQ.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		Member m = (Member)session.getAttribute("m");
    
    	ChellengeMemberData cmd = (ChellengeMemberData)session.getAttribute("cmd"); 
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <div class=\"header-top\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/logo-plogging.png\" alt=\"plogging\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-center\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/img-main-title.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-button\">\r\n");
      out.write("                <a href=\"\" >지구쓰담 후원하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-bottom\">\r\n");
      out.write("            <ul class=\"header-menu\">\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">줍깅 캠페인</a></li>\r\n");
      out.write("                <li><a href=\"/chellengeFrm.do?reqPage=1\">쓰담위크 퀘스트</a></li>\r\n");
      out.write("                <li><a href=\"/storyList.do?reqPage=1\">쓰담 스토리</a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">쓰담 굿즈</a></li>\r\n");
      out.write("                <li><a href=\"/noticeList.do?reqPage=1\">쓰담 소식</a></li>\r\n");
      out.write("                <li><a href=\"/plogging.do\">진행중인 플로깅</a></li>\r\n");
      out.write("                ");
if(m!=null && m.getMemberLevel() == 1) {
      out.write("\r\n");
      out.write("                <li><a href=\"/admin.do\">관리자</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"util-menu\">\r\n");
      out.write("                ");
if(m!=null){
      out.write("\r\n");
      out.write("                <li><a href=\"/mypage.do\">");
      out.print(m.getNickname());
      out.write("</a></li>\r\n");
      out.write("                <li><a href=\"/logout.do\">로그아웃</a></li>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <li><a href=\"/common/signinFrm.jsp\">로그인/회원가입</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- // header -->");
      out.write("\r\n");
      out.write("	<div class=\"page-content\">\r\n");
      out.write("		<div class=\"page-title\">쓰<span class=\"page-title2\">담</span>소식</div>\r\n");
      out.write("		<div class=\"notice-navi-wrap\">\r\n");
      out.write("			<div class=\"navi-wrap\">\r\n");
      out.write("				<div><a href=\"/noticeList.do?reqPage=1\">공지사항</a></div>\r\n");
      out.write("				<div><a href=\"/FAQ.do\">FAQ</a></div>\r\n");
      out.write("				<div><a href=\"/inquiryFrm.do\">문의하기</a></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"FAQ-wrap5\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"question-icon5\">\r\n");
      out.write("						<span>Q</span>\r\n");
      out.write("						<span class=\"faq-font\">어린이 또는 청소년의 참여가 가능한가요?</span>\r\n");
      out.write("						<img src=\"/img/news/arrowDown.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"question-content5\">\r\n");
      out.write("					가능합니다. 다만 보호자 동행하에 안전하게 쓰담 활동을 진행해주시기 바랍니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"FAQ-wrap4\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"question-icon4\">\r\n");
      out.write("						<span>Q</span>\r\n");
      out.write("						<span class=\"faq-font\">쓰담달리기를 할 때 유의해야할 점이 있나요?</span>\r\n");
      out.write("						<img src=\"/img/news/arrowDown.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"question-content4\">\r\n");
      out.write("					코로나19 방역수칙을 준수하여 반드시 마스크를 착용하여 주시고, 가능한 1인 개별 활동으로 진행해주세요. 개인의 부주의로 안전문제가 발생할 경우, 주최 측에서는 책임지지 않습니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"FAQ-wrap\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"question-icon\">\r\n");
      out.write("						<span>Q</span>\r\n");
      out.write("						<span class=\"faq-font\">신청은 혼자 했는데 활동을 친구 또는 가족과 했습니다. 쓰담 기록지를 모두 제출하면 인정되나요?</span>\r\n");
      out.write("						<img src=\"/img/news/arrowDown.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"question-content\">\r\n");
      out.write("					사전신청을 한 인원에 한해서만 기록지 제출이 인정됩니다. 참여자 개별 사전 신청 바랍니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"FAQ-wrap2\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"question-icon2\">\r\n");
      out.write("						<span>Q</span>\r\n");
      out.write("						<span class=\"faq-font\">참가신청만 하면 봉사시간이 인증되나요?</span>\r\n");
      out.write("						<img src=\"/img/news/arrowDown.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"question-content2\">\r\n");
      out.write("					아니요, 활동 후 반드시 쓰담 기록지를 제출해주셔야 합니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"FAQ-wrap3\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"question-icon3\">\r\n");
      out.write("						<span>Q</span>\r\n");
      out.write("						<span class=\"faq-font\">쓰담 달리기 후 쓰레기는 어떻게 처리하나요?</span>\r\n");
      out.write("						<img src=\"/img/news/arrowDown.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"question-content3\">\r\n");
      out.write("					쓰담기록지 작성을 위해 쓰레기의 종류와 수량을 파악한 뒤, 분리배출 해주시기 바랍니다. 부패되거나 형태가 변형된 쓰레기는 일반쓰레기로 버려주세요.\r\n");
      out.write("					</p>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\".question-icon>img\").on(\"click\",function(){\r\n");
      out.write("			if($(this).parent().hasClass(\"active\")) {\r\n");
      out.write("				$(this).parent().removeClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"0px\").css(\"padding-top\",\"\");\r\n");
      out.write("				$(\".question-icon>img\").attr(\"src\",\"/img//news/arrowDown.png\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(this).parent().addClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"60px\").css(\"padding-top\",\"35px\");\r\n");
      out.write("				$(\".question-icon>img\").attr(\"src\",\"/img//news/arrowUp.png\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(\".question-icon2>img\").on(\"click\",function(){\r\n");
      out.write("			if($(this).parent().hasClass(\"active\")) {\r\n");
      out.write("				$(this).parent().removeClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"0px\").css(\"padding-top\",\"\");\r\n");
      out.write("				$(\".question-icon2>img\").attr(\"src\",\"/img//news/arrowDown.png\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(this).parent().addClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"60px\").css(\"padding-top\",\"35px\");\r\n");
      out.write("				$(\".question-icon2>img\").attr(\"src\",\"/img//news/arrowUp.png\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(\".question-icon3>img\").on(\"click\",function(){\r\n");
      out.write("			if($(this).parent().hasClass(\"active\")) {\r\n");
      out.write("				$(this).parent().removeClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"0px\").css(\"padding-top\",\"\");\r\n");
      out.write("				$(\".question-icon3>img\").attr(\"src\",\"/img//news/arrowDown.png\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(this).parent().addClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"60px\").css(\"padding-top\",\"35px\");\r\n");
      out.write("				$(\".question-icon3>img\").attr(\"src\",\"/img//news/arrowUp.png\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(\".question-icon4>img\").on(\"click\",function(){\r\n");
      out.write("			if($(this).parent().hasClass(\"active\")) {\r\n");
      out.write("				$(this).parent().removeClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"0px\").css(\"padding-top\",\"\");\r\n");
      out.write("				$(\".question-icon4>img\").attr(\"src\",\"/img//news/arrowDown.png\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(this).parent().addClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"60px\").css(\"padding-top\",\"35px\");\r\n");
      out.write("				$(\".question-icon4>img\").attr(\"src\",\"/img//news/arrowUp.png\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(\".question-icon5>img\").on(\"click\",function(){\r\n");
      out.write("			if($(this).parent().hasClass(\"active\")) {\r\n");
      out.write("				$(this).parent().removeClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"0px\").css(\"padding-top\",\"\");\r\n");
      out.write("				$(\".question-icon5>img\").attr(\"src\",\"/img//news/arrowDown.png\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(this).parent().addClass(\"active\");\r\n");
      out.write("				$(this).parent().next().css(\"height\",\"60px\").css(\"padding-top\",\"35px\");\r\n");
      out.write("				$(\".question-icon5>img\").attr(\"src\",\"/img//news/arrowUp.png\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer_wrap\">\r\n");
      out.write("        <div class=\"footer_text\">\r\n");
      out.write("            <p>재단법인 환경재단</p>\r\n");
      out.write("            <p>대표 진민호 대표전화 02-1111-1111 fax 02-111-1111</p>\r\n");
      out.write("            <p>문의 이메일 jinminho@kh.or.kr</p>\r\n");
      out.write("            <p>서울시 영등포구</p>\r\n");
      out.write("            <p>사업자 등록번호 111-11-11111</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침</a></li> \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- // footer -->");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
