/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-27 01:50:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.Console;
import com.earthpurging.index.model.vo.ChellengeRank;
import java.util.ArrayList;
import com.earthpurging.index.model.vo.ChellengeMemberData;
import com.earthpurging.member.model.vo.Member;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1664243429901L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663920910595L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.earthpurging.index.model.vo.ChellengeMemberData");
    _jspx_imports_classes.add("com.earthpurging.index.model.vo.ChellengeRank");
    _jspx_imports_classes.add("com.earthpurging.member.model.vo.Member");
    _jspx_imports_classes.add("java.io.Console");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    //[1번로직] 챌린지 1~5등 선정 값 데이터
    ArrayList<ChellengeRank> list = (ArrayList<ChellengeRank>)request.getAttribute("list");
	
    ChellengeMemberData all = (ChellengeMemberData)request.getAttribute("all");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://fonts.cdnfonts.com/css/dunggeunmo\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/index_content.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/index_button.css\">\r\n");
      out.write("    <!-- 제이쿼리 사용 -->\r\n");
      out.write("    <script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- swiper 사용 CDN-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css\"/>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!--차트js 사용 CDN-->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js\"></script>\r\n");
      out.write("<title>지구푸르깅</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		Member m = (Member)session.getAttribute("m");
    
    	ChellengeMemberData cmd = (ChellengeMemberData)session.getAttribute("cmd"); 
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <div class=\"header-top\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/logo-plogging.png\" alt=\"plogging\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-center\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/img-main-title.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-button\">\r\n");
      out.write("                <a href=\"\" >지구쓰담 후원하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-bottom\">\r\n");
      out.write("            <ul class=\"header-menu\">\r\n");
      out.write("                <li><a href=\"/\">줍깅 캠페인</a></li>\r\n");
      out.write("                <li><a href=\"/chellengeFrm.do?reqPage=1\">쓰담위크 퀘스트</a></li>\r\n");
      out.write("                <li><a href=\"/storyList.do?reqPage=1\">쓰담 스토리</a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">쓰담 굿즈</a></li>\r\n");
      out.write("                <li><a href=\"/noticeList.do?reqPage=1\">쓰담 소식</a></li>\r\n");
      out.write("                <li><a href=\"/plogging.do\">진행중인 플로깅</a></li>\r\n");
      out.write("                ");
if(m!=null && m.getMemberLevel() == 1) {
      out.write("\r\n");
      out.write("                <li><a href=\"/admin.do\">관리자</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"util-menu\">\r\n");
      out.write("                ");
if(m!=null){
      out.write("\r\n");
      out.write("                <li><a href=\"/mypage.do\">");
      out.print(m.getNickname());
      out.write("</a></li>\r\n");
      out.write("                <li><a href=\"/logout.do\">로그아웃</a></li>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <li><a href=\"/common/signinFrm.jsp\">로그인/회원가입</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- // header -->");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- content -->\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <!-- Banner section-->\r\n");
      out.write("            <section id=\"banner\">\r\n");
      out.write("                <div class=\"banner-container\">\r\n");
      out.write("                    <div class=\"banner-wrap\"></div>\r\n");
      out.write("                    <div class=\"banner-img\"></div>\r\n");
      out.write("                    <div class=\"banner-content\">\r\n");
      out.write("                        <img src=\"/img/index/index_main_bottom_title.png\" alt=\"\"><br>\r\n");
      out.write("                        <span>우리의 보금자리 지구 푸르깅푸르깅!</span><br>\r\n");
      out.write("                        <span>더 많은 지역, 더 많은 쓰레기를 쓰담 할 수 있도록 함께 해주세요.</span><br>\r\n");
      out.write("                        <div><a href=\"/mainPage.do\">지구푸르깅 후원하기</a></div>\r\n");
      out.write("                        <a href=\"#main\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Banner section-->\r\n");
      out.write("            \r\n");
      out.write("            <!-- Main section-->\r\n");
      out.write("            <section id=\"main\">\r\n");
      out.write("                <div class=\"main-container\">\r\n");
      out.write("                    <div class=\"main-wrap\">\r\n");
      out.write("                        <div class=\"main-wrap-top\">\r\n");
      out.write("                            <span>플라스틱 소비가 지금과 같다면<br>\r\n");
      out.write("                                2050년에는 바다에 물고기보다 플라스틱 쓰레기가 더 많아질 것이다.</span><br>\r\n");
      out.write("                                <span>-2016 세계경제포럼-</span><br>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"main-wrap-bottom\">\r\n");
      out.write("                            <span>이대로 <br>\r\n");
      out.write("                            꾸준히 버리시겠습니까?</span><br>\r\n");
      out.write("                            <span>- 지구푸르깅 -</span><br>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <img src=\"/img/index/index_main_img.jpg\" alt=\"\">\r\n");
      out.write("                    <div class=\"main-title\">\r\n");
      out.write("                        <div class=\"main-title-top\">\r\n");
      out.write("                            바다에 버려진 쓰레기는 어디서 온거죠?\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"main-title-middle\">\r\n");
      out.write("                            우리나라 바다에 버려지는 쓰레기의 <span class=\" bolder\">90% 이상의 플라스틱,</span><Br>\r\n");
      out.write("                            그중 <span class=\" bolder\">60%</span>는 우리 <span class=\" bolder\">일상 생활에서 발생된 쓰레기</span>입니다.<br><br><br>\r\n");
      out.write("                            <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7XrxTrejx8w\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"main-title-bottom\">\r\n");
      out.write("                            <div class=\"main-bottom-title\">\r\n");
      out.write("                                지구에 남겨진 쓰레기, 이대로 괜찮을까요?\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"main-bottom-content\">\r\n");
      out.write("                                <img src=\"img/common/img-main-title.png\" alt=\"\"><br>\r\n");
      out.write("                                <strong>이제는 우리의 손으로 지구를 푸르깅 할 때!</strong>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <p>플라스틱 쓰레기로부터 생명을 지키고,</p>\r\n");
      out.write("                                <p>깨끗한 지구를 만들기 위해</p>\r\n");
      out.write("                                <p>지구의 쓰레기를 담습니다.</p>\r\n");
      out.write("                                <p>지구 푸르깅 캠페인은 심각한 플라스틱 쓰레기 문제를 알리고</p>\r\n");
      out.write("                                <p>국내 환경 단체와 함께 환경 회복을 위한 정화 활동을 진행합니다.</p>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#todo\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Main section-->\r\n");
      out.write("            \r\n");
      out.write("            <!-- Todo section-->\r\n");
      out.write("            <section id=\"todo\">\r\n");
      out.write("                <div class=\"todo-container\">\r\n");
      out.write("                    <div class=\"todo-title\">이달의 지구푸르깅 스토리</div>\r\n");
      out.write("                    <div class=\"todo-content\">\r\n");
      out.write("                        <div class=\"todo-content-wrap\">\r\n");
      out.write("                            <div class=\"todo-content-title\">지구푸르깅과 함께하는 사람들의 이야기</div>\r\n");
      out.write("                            <div class=\"todo-content-sub-title\">우리의 일상으로<img src=\"/img/index/index_todo_content_line.png\">한 지구의 일상을 지키다.</div>\r\n");
      out.write("                            <div class=\"todo-content-left\"></div>\r\n");
      out.write("                            <div class=\"todo-content-img\"><img src=\"/img/index/people3.png\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"todo-content-msg\">\r\n");
      out.write("                                <p class=\"name\">KH 마법소녀 현주 님</p>\r\n");
      out.write("                                <h4>하루를 살다가 쓰레기를 보면<br>\r\n");
      out.write("                                    지구가 생각나요.<br>\r\n");
      out.write("                                    평범한 하루가 간절한 지구에게<br>\r\n");
      out.write("                                    힘이 되고 싶어요!\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <p class=\"msg\">\"제가 쓰레기로 피해를 경험하지 않았잖아요.<br>\r\n");
      out.write("                                감히 피해본 동물들의 마음을 헤아릴 수 없지만,<br>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                지구푸르깅 후원을 통해서 아이들을 기억하고<br>\r\n");
      out.write("                                깨끗한 환경을 선물 해 줄 수 있어서 감사해요.\"\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <a href=\"#\"><div class=\"todo-content-support\">후원하기</div></a>\r\n");
      out.write("                            <div class=\"todo-fake-box\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"todo-content-right\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#ploggings\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Todo section-->\r\n");
      out.write("\r\n");
      out.write("            <!-- Ploggings section-->\r\n");
      out.write("            <section id=\"ploggings\">\r\n");
      out.write("                <div class=\"ploggings-container\">\r\n");
      out.write("                    <div class=\"ploggings-title\">우리는 어떤 활동을 하나요?</div>\r\n");
      out.write("                    <div class=\"plogging-content\">\r\n");
      out.write("                        <div class=\"plogging-content-left\"><img src=\"/img/index/index_ploggings_img.png\" alt=\"\"></div>\r\n");
      out.write("                        <div class=\"plogging-content-right\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <span class=\"p-title\">플로깅은 <span class=\"p-color-orange\">‘이삭을 줍는다’</span>는 뜻인 스웨덴어 <span  class=\"p-color-orange\">plocka upp</span>과 영어 단어 <span  class=\"p-color-red\">jogging(조깅)</span>이 합쳐져 생긴 합성어입니다.</span>\r\n");
      out.write("                                <br><br>\r\n");
      out.write("                                이는 조깅하면서 쓰레기를 줍는 행동으로 2016년 스웨덴에서 처음 시작된 운동으로 플로깅(plogging) 자세는 스쿼트나 런지 운동 자세와 비슷하여 칼로리 소모량이 일반 조깅보다 약 50kcal를 더 소모한다는 연구결과가 발표되며 건강과 환경 두 마리 토끼를 잡을 수 있다는 인식과 함께 2030 세대의 트렌드로 자리잡았습니다.\r\n");
      out.write("                                <br><br>\r\n");
      out.write("                                플로깅의 발상지 스웨덴을 시작으로 점차 북유럽으로 확산되어 현재는 국내를 비롯하여 전 세계적인 운동 트렌드로 자리매김하고 있습니다. \r\n");
      out.write("                            </p>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#ranking\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Ploggings section-->\r\n");
      out.write("	\r\n");
      out.write("			");
if(cmd!=null){
      out.write("\r\n");
      out.write("			<!-- myinfo section-->\r\n");
      out.write("            <section id=\"myinfo\">\r\n");
      out.write("                <div class=\"myinfo-container\">\r\n");
      out.write("                    <div class=\"myinfo-title\">접속자 정보</div>\r\n");
      out.write("                    <div class=\"myinfo-content\">\r\n");
      out.write("                        <div class=\"myinfo-wrap\">\r\n");
      out.write("                            <!-- Slider main container -->\r\n");
      out.write("                            <div class=\"myinfo\">\r\n");
      out.write("                                <!-- Additional required wrapper -->\r\n");
      out.write("                                <div class=\"myinfo-wrapper\">\r\n");
      out.write("                                    <!-- Slides -->\r\n");
      out.write("                                    <div class=\"myinfo-slide\">\r\n");
      out.write("                                        <div class=\"myinfo-slide-top\">현재 당신의 <span>'Quest Point Boad'</span> 입니다.</div>\r\n");
      out.write("                                        <div class=\"myinfo-slide-middle left\">\r\n");
      out.write("                                            <div class=\"myinfo-slide-middle-title\">당신의 포인트</div>\r\n");
      out.write("                                            <div class=\"myinfo-slide-middle-content\"><span>");
      out.print(cmd.getQuestPoint() );
      out.write("</span> Point</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"myinfo-slide-middle middle\">\r\n");
      out.write("                                            <div class=\"myinfo-slide-middle-title\">당신의 이름</div>\r\n");
      out.write("                                            <div class=\"myinfo-slide-middle-content middle\"><span>:</span> ");
      out.print(m.getMemberName() );
      out.write("</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"myinfo-slide-middle right\">\r\n");
      out.write("                                            <div class=\"myinfo-slide-middle-title\">자기소개</div>\r\n");
      out.write("                                            <div class=\"myinfo-slide-middle-content last\"><span> : </span>");
      out.print(m.getMemberIntro());
      out.write("</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"myinfo-slide-bottom\">\r\n");
      out.write("                                            <div class=\"myinfo-slide-bottom-title\">현재 당신의 총 플로깅 줍것들</div>\r\n");
      out.write("                                            <div class=\"myinfo-slide-bottom-content\">\r\n");
      out.write("                                                <ul>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-recycle-can.png\" alt=\"\"></div>\r\n");
      out.write("                                                        ");
      out.print(cmd.getQuestCan());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-recycle-glass.png\" alt=\"\"></div>\r\n");
      out.write("                                                        ");
      out.print(cmd.getQuestGlass());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-recycle-paper.png\" alt=\"\"></div>\r\n");
      out.write("                                                       	");
      out.print(cmd.getQuestPaper());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-recycle-plastic.png\" alt=\"\"></div>\r\n");
      out.write("                                                        ");
      out.print(cmd.getQuestPla());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-recycle-plastic2.png\" alt=\"\"></div>\r\n");
      out.write("                                                        ");
      out.print(cmd.getQuestWrapper());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-trash-tobacco.png\" alt=\"\"></div>\r\n");
      out.write("                                                        ");
      out.print(cmd.getQuestTabacoo());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <div class=\"li-img\"><img src=\"/img/img-plogging.png\" alt=\"\"></div>\r\n");
      out.write("                                                        Level: ");
      out.print(cmd.getMemberLevel());
      out.write("\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                            \r\n");
      out.write("                                <!-- If we need scrollbar -->\r\n");
      out.write("                                <div class=\"swiper-scrollbar\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#chart\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End myinfo section-->\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("            <!-- Ranking section-->\r\n");
      out.write("            <section id=\"ranking\">\r\n");
      out.write("                <div class=\"ranking-container\">\r\n");
      out.write("                    <div class=\"ranking-title\">쓰담 퀘스트 현재 랭킹</div>\r\n");
      out.write("                    <div class=\"ranking-content\">\r\n");
      out.write("                        <div class=\"swiper-wrap\">\r\n");
      out.write("                            <!-- Slider main container -->\r\n");
      out.write("                            <div class=\"swiper\">\r\n");
      out.write("                                <!-- Additional required wrapper -->\r\n");
      out.write("                                <div class=\"swiper-wrapper\">\r\n");
      out.write("                                <!-- Slides -->\r\n");
      out.write("                                \r\n");
      out.write("                                ");
for(ChellengeRank cr : list){ 
      out.write("\r\n");
      out.write("                        		\r\n");
      out.write("                                <div class=\"swiper-slide\">\r\n");
      out.write("                                    <div class=\"swiper-slide-wrap\"></div>\r\n");
      out.write("                                    <div class=\"swiper-slide-content\">\r\n");
      out.write("                                        <div class=\"swiper-slide-content-top\">\r\n");
      out.write("                                            <img src=\"/img/index/index_main_bottom_title.png\" alt=\"\"><br>\r\n");
      out.write("                                            Quest TOP Player\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"swiper-slide-content-middle\">\r\n");
      out.write("                                            <div class=\"slide-content-left\">\r\n");
      out.write("                                                <div class=\"slide-content-left-top\">총 포인트<br><span>");
      out.print(cr.getQuestPoint() );
      out.write("</span> POINT</div>\r\n");
      out.write("                                                <div class=\"slide-content-left-middle\">\r\n");
      out.write("                                                    <ul>\r\n");
      out.write("                                                        <li>캔<br>");
      out.print( cr.getQuestCan() );
      out.write("</li>\r\n");
      out.write("                                                        <li>플라스틱<br>");
      out.print( cr.getQuestPla() );
      out.write("</li>\r\n");
      out.write("                                                        <li>병<br>");
      out.print(cr.getQuestGlass() );
      out.write("</li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                    <ul>\r\n");
      out.write("                                                        <li>종이<br>");
      out.print(cr.getQuestPaper() );
      out.write("</li>\r\n");
      out.write("                                                        <li>비닐<br>");
      out.print(cr.getQuestWrapper() );
      out.write("</li>\r\n");
      out.write("                                                        <li>담배꽁초<br>");
      out.print(cr.getQuestTabacoo() );
      out.write("</li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"slide-content-sub\">\r\n");
      out.write("                                                        <h3>닉네임 : ");
      out.print(cr.getNickName());
      out.write(" 님</h3>\r\n");
      out.write("                                                    <p>");
      out.print(cr.getMemberIntro() );
      out.write("</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"slide-content-right\">\r\n");
      out.write("                                                <div class=\"slide-content-name\">전체 '");
      out.print(cr.getRank());
      out.write("'등<br><span>");
      out.print(cr.getMemberName() );
      out.write("</span> 님</div>\r\n");
      out.write("                                                <div class=\"slide-content-img\">\r\n");
      out.write("                                                <!-- 인물사진 -->\r\n");
      out.write("                                                <img src=\"/upload/chellenge/");
      out.print(cr.getPhotoPath());
      out.write("\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"swiper-slide-content-bottom\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <img src=\"/img/index/test6.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                        		");
} 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- If we need pagination -->\r\n");
      out.write("                                <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                            \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- If we need navigation buttons -->\r\n");
      out.write("                            <div class=\"swiper-button-prev\"></div>\r\n");
      out.write("                            <div class=\"swiper-button-next\"></div>\r\n");
      out.write("                        \r\n");
      out.write("                            <!-- If we need scrollbar -->\r\n");
      out.write("                            <div class=\"swiper-scrollbar\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#chart\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Ranking section-->\r\n");
      out.write("            \r\n");
      out.write("            <!-- Chart section-->\r\n");
      out.write("            <section id=\"chart\">\r\n");
      out.write("                <div class=\"chart-container\">\r\n");
      out.write("                    <div class=\"chart-title\">우리의 플로깅 활동 차트</div>\r\n");
      out.write("                    <div class=\"chart-content\">\r\n");
      out.write("                        <div class=\"chart-wrap\">\r\n");
      out.write("                            <canvas id=\"bar-chart\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"#support\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Chart section-->\r\n");
      out.write("\r\n");
      out.write("            <!-- Support section-->\r\n");
      out.write("            <section id=\"support\">\r\n");
      out.write("                <div class=\"support-container\">\r\n");
      out.write("                    <div class=\"support-wrap\"></div>\r\n");
      out.write("                    <div class=\"support-img\"></div>\r\n");
      out.write("                    <div class=\"support-content\">\r\n");
      out.write("                        <p>쓰레기로 고통 받는 지구에겐</p><br>\r\n");
      out.write("                        <p>바로 오늘의 도움이 필요합니다</p><br>\r\n");
      out.write("                        <div><a href=\"#\">지구푸르깅 후원하기</a></div>\r\n");
      out.write("                        <a href=\"#\" class=\"button style2 down anchored\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- End Support section-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- // content -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer_wrap\">\r\n");
      out.write("        <div class=\"footer_text\">\r\n");
      out.write("            <p>재단법인 환경재단</p>\r\n");
      out.write("            <p>대표 진민호 대표전화 02-1111-1111 fax 02-111-1111</p>\r\n");
      out.write("            <p>문의 이메일 jinminho@kh.or.kr</p>\r\n");
      out.write("            <p>서울시 영등포구</p>\r\n");
      out.write("            <p>사업자 등록번호 111-11-11111</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침</a></li> \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- // footer -->");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<!-- script Line -->\r\n");
      out.write("    <script>\r\n");
      out.write("    setTimeout(function(){\r\n");
      out.write("        name = $(\".name\");\r\n");
      out.write("        let count = 0;\r\n");
      out.write("    },5000);\r\n");
      out.write("\r\n");
      out.write("    $(window).on(\"load\", function () {\r\n");
      out.write("    function fade() {\r\n");
      out.write("      let animation_height = $(window).innerHeight() * 0.5;\r\n");
      out.write("      let ratio = Math.round((1 / animation_height) * 10000) / 10000;\r\n");
      out.write("    $(\".ploggings-container\").each(function () {\r\n");
      out.write("        let objectTop = $(this).offset().top;\r\n");
      out.write("        let windowBottom = $(window).scrollTop() + $(window).innerHeight();\r\n");
      out.write("        if (objectTop < windowBottom) {\r\n");
      out.write("        if (objectTop < windowBottom - animation_height) {\r\n");
      out.write("            $(this).css({\r\n");
      out.write("            transition: \"opacity 0.1s linear\",\r\n");
      out.write("            transition: \"left 0.2s linear\",\r\n");
      out.write("            opacity: 1,\r\n");
      out.write("            left: \"0px\",\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            $(this).css({\r\n");
      out.write("            transition: \"opacity 0.7s linear\",\r\n");
      out.write("              opacity: (windowBottom - objectTop) * ratio,\r\n");
      out.write("            transition: \"left 0.7s linear\",\r\n");
      out.write("              left: `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${200 * (1 - (windowBottom - objectTop) * ratio)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px`,\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        } else {\r\n");
      out.write("        $(this).css({\r\n");
      out.write("            opacity: 0,\r\n");
      out.write("            left: \"200px\",\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $(window).scroll( function(){\r\n");
      out.write("        $('.main-title-middle').each( function(i){\r\n");
      out.write("            \r\n");
      out.write("            var bottom_of_element = $(this).offset().top + $(this).outerHeight();\r\n");
      out.write("            var bottom_of_window = $(window).scrollTop() + $(window).height();\r\n");
      out.write("            \r\n");
      out.write("            if( bottom_of_window > bottom_of_element ){\r\n");
      out.write("                $(this).animate({'opacity':'1','margin-left':'0px'},900);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        }); \r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $(window).scroll( function(){\r\n");
      out.write("        $('.main-wrap-bottom').each( function(i){\r\n");
      out.write("            \r\n");
      out.write("            var bottom_of_element = $(this).offset().top + $(this).outerHeight();\r\n");
      out.write("            var bottom_of_window = $(window).scrollTop() + $(window).height();\r\n");
      out.write("            \r\n");
      out.write("            if( bottom_of_window > bottom_of_element ){\r\n");
      out.write("                $(this).animate({'opacity':'1','margin-left':'0px'},900);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        }); \r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $(window).scroll( function(){\r\n");
      out.write("        $('.main-wrap-top').each( function(i){\r\n");
      out.write("            \r\n");
      out.write("            var bottom_of_element = $(this).offset().top + $(this).outerHeight();\r\n");
      out.write("            var bottom_of_window = $(window).scrollTop() + $(window).height();\r\n");
      out.write("            \r\n");
      out.write("            if( bottom_of_window > bottom_of_element ){\r\n");
      out.write("                $(this).animate({'opacity':'1','margin-left':'0px'},900);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        }); \r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\".ploggings-container\").css({\r\n");
      out.write("    opacity: 0,\r\n");
      out.write("    left: \"200px\",\r\n");
      out.write("    });\r\n");
      out.write("    fade();\r\n");
      out.write("    $(window).scroll(function () {\r\n");
      out.write("    fade();\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" const swiper = new Swiper('.swiper', {\r\n");
      out.write(" 	  // Optional parameters\r\n");
      out.write(" 	  direction: 'vertical',\r\n");
      out.write(" 	  loop: true,\r\n");
      out.write("\r\n");
      out.write(" 	  // If we need pagination\r\n");
      out.write(" 	  pagination: {\r\n");
      out.write(" 	    el: '.swiper-pagination',\r\n");
      out.write(" 	  },\r\n");
      out.write("\r\n");
      out.write(" 	  // Navigation arrows\r\n");
      out.write(" 	  navigation: {\r\n");
      out.write(" 	    nextEl: '.swiper-button-next',\r\n");
      out.write(" 	    prevEl: '.swiper-button-prev',\r\n");
      out.write(" 	  },\r\n");
      out.write("\r\n");
      out.write(" 	  // And if we need scrollbar\r\n");
      out.write(" 	  scrollbar: {\r\n");
      out.write(" 	    el: '.swiper-scrollbar',\r\n");
      out.write(" 	  },\r\n");
      out.write(" 	});\r\n");
      out.write("\r\n");
      out.write("//차트.js 스크립트\r\n");
      out.write("new Chart(document.getElementById(\"bar-chart\"), {\r\n");
      out.write("    type: 'bar',\r\n");
      out.write("    data: {\r\n");
      out.write("      labels: [\"캔 개수\", \"플라스틱 개수\", \"병 개수\", \"종이 개수\", \"비닐 개수\", \"담배꽁초 개수\"],\r\n");
      out.write("      datasets: [\r\n");
      out.write("        {\r\n");
      out.write("          label: \"수집된 쓰레기 총 개수\",\r\n");
      out.write("          backgroundColor: [\"#3e95ff\", \"#8e5ea2\",\"#3cba9f\",\"#e8c3b9\",\"#c45850\",\"#3e95cd\"],\r\n");
      out.write("          ");
if(all!=null){
      out.write("\r\n");
      out.write("    	  data:\r\n");
      out.write("    		[");
      out.print(all.getQuestCan());
      out.write(",\r\n");
      out.write("	    	  ");
      out.print(all.getQuestPla());
      out.write(",\r\n");
      out.write("	    	  ");
      out.print(all.getQuestGlass());
      out.write(",\r\n");
      out.write("	    	  ");
      out.print(all.getQuestPaper());
      out.write(",\r\n");
      out.write("	    	  ");
      out.print(all.getQuestWrapper());
      out.write(",\r\n");
      out.write("	    	  ");
      out.print(all.getQuestTabacoo());
      out.write("]\r\n");
      out.write("		      ");
}else{
      out.write("\r\n");
      out.write("	      data: [,,,,,]\r\n");
      out.write("	      ");
}
      out.write("\r\n");
      out.write("        },{\r\n");
      out.write("          ");
if(cmd!=null){
      out.write("\r\n");
      out.write("          label: \"");
      out.print(cmd.getMemberName());
      out.write("님의 수집 총 개수\",\r\n");
      out.write("          ");
}else{
      out.write("\r\n");
      out.write("          label: \"로그인 시 데이터를 조회 할 수 있습니다!!!\",\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("          backgroundColor: [\"#3cba9f\", \"#8e5ed2\",\"#3cbaff\",\"#e8c3c9\",\"#c458f0\",\"#3e958d\"],\r\n");
      out.write("          borderWidth: 5,\r\n");
      out.write("          ");
if(cmd!=null){
      out.write("\r\n");
      out.write("        	  data:\r\n");
      out.write("        	[");
      out.print(cmd.getQuestCan());
      out.write(",\r\n");
      out.write("        	  ");
      out.print(cmd.getQuestPla());
      out.write(",\r\n");
      out.write("        	  ");
      out.print(cmd.getQuestGlass());
      out.write(",\r\n");
      out.write("        	  ");
      out.print(cmd.getQuestPaper());
      out.write(",\r\n");
      out.write("        	  ");
      out.print(cmd.getQuestWrapper());
      out.write(",\r\n");
      out.write("        	  ");
      out.print(cmd.getQuestTabacoo());
      out.write("]\r\n");
      out.write("          ");
}else{
      out.write("\r\n");
      out.write("          data: [,,,,,]\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("      ]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("      legend: { maintainAspectRatio: false, display: true, labels: {\r\n");
      out.write("					fontSize: 17,\r\n");
      out.write("				}\r\n");
      out.write("            },\r\n");
      out.write("      ticks: {\r\n");
      out.write("          stepSize: 10, //y축 간격\r\n");
      out.write("          suggestedMin: 0,//y축 최소 값\r\n");
      out.write("          suggestedMax: 200,//y축 최대값\r\n");
      out.write("      },\r\n");
      out.write("      title: {\r\n");
      out.write("        display: true,\r\n");
      out.write("        text: '현재까지 모인 쓰레기의 총 개수',\r\n");
      out.write("        font:{\r\n");
      out.write("            size:50,\r\n");
      out.write("            weight: 'bold',\r\n");
      out.write("            lineHeight: 1.2\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    google.charts.load('50', {'packages':['line','controls']});\r\n");
      out.write("chartDrowFun.chartDrow(); //chartDrow() 실행\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- End script Line -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
