/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-26 09:09:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.earthpurging.index.model.vo.ChellengeMemberData;
import com.earthpurging.member.model.vo.Member;

public final class plogging_005fdetail2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1664172377681L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663920910595L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.earthpurging.index.model.vo.ChellengeMemberData");
    _jspx_imports_classes.add("com.earthpurging.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://fonts.cdnfonts.com/css/dunggeunmo\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/index_content.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/index_button.css\">\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/css/plogging_detail1.css\">\r\n");
      out.write("	\r\n");
      out.write("	<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<title>지구푸르깅</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		Member m = (Member)session.getAttribute("m");
    
    	ChellengeMemberData cmd = (ChellengeMemberData)session.getAttribute("cmd"); 
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <div class=\"header-top\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/logo-plogging.png\" alt=\"plogging\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-center\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/img-main-title.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-button\">\r\n");
      out.write("                <a href=\"\" >지구쓰담 후원하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-bottom\">\r\n");
      out.write("            <ul class=\"header-menu\">\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">줍깅 캠페인</a></li>\r\n");
      out.write("                <li><a href=\"/chellengeFrm.do?reqPage=1\">쓰담위크 퀘스트</a></li>\r\n");
      out.write("                <li><a href=\"/storyList.do?reqPage=1\">쓰담 스토리</a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">쓰담 굿즈</a></li>\r\n");
      out.write("                <li><a href=\"/noticeList.do?reqPage=1\">쓰담 소식</a></li>\r\n");
      out.write("                <li><a href=\"/plogging.do\">진행중인 플로깅</a></li>\r\n");
      out.write("                ");
if(m!=null && m.getMemberLevel() == 1) {
      out.write("\r\n");
      out.write("                <li><a href=\"/admin.do\">관리자</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"util-menu\">\r\n");
      out.write("                ");
if(m!=null){
      out.write("\r\n");
      out.write("                <li><a href=\"/mypage.do\">");
      out.print(m.getNickname());
      out.write("</a></li>\r\n");
      out.write("                <li><a href=\"/logout.do\">로그아웃</a></li>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <li><a href=\"/common/signinFrm.jsp\">로그인/회원가입</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- // header -->");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("     <!-- content -->\r\n");
      out.write("    <form action=\"/ploggingDetail2.do\" method=\"get\" onsubmit=\"return onchecked()\">\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <div class=\"page-content-img\"><img src=\"/img/index/ploggings_img2.png\" alt=\"\"></div>\r\n");
      out.write("            <div class=\"page-content-map\">\r\n");
      out.write("                <div class=\"map-title\">위치 정보</div>\r\n");
      out.write("                <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3163.903093515661!2d126.8945896152442!3d37.5337815798041!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357c9edb0d6df1b1%3A0x8ae903d3dc14b683!2zS0jsoJXrs7TqtZDsnKHsm5Ag64u57IKw7KeA7JuQ!5e0!3m2!1sko!2skr!4v1663743515956!5m2!1sko!2skr\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"page-content-apply\">\r\n");
      out.write("                <div class=\"apply-title\">참여 신청 하기</div>\r\n");
      out.write("                <div class=\"apply-content\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"apply-join\">1.이름</li>\r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                            <input type=\"text\" id=\"crew_name\" name=\"crew_name\" placeholder=\"이름을 입력해주세요\" class=\"apply-join-input\" required>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"apply-join\">2.생년월일<br><span class=\"apply-join-sub\">생년월일 숫자 6자리만 기재</span></li>\r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                            <input type=\"text\" id=\"crew_birth\" name=\"crew_birth\" placeholder=\"ex)960607\" class=\"apply-join-input\" required>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"apply-join\">3. 희망하는 활동 장소<br><span class=\"apply-join-sub\">팀원들과 사전 상의 후 동일하게 기재<span class=\"apply-join-sub red\">(복수체크 불가능)</span></span></li>\r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                            <input type='radio' name='crew_place' id=\"1_area\" value=\"잠실한강공원\" checked>\r\n");
      out.write("                            <label for=\"1_area\">잠실 한강공원</label>\r\n");
      out.write("                            <input type='radio' name='crew_place' id=\"2_area\" value=\"뚝섬한강공원\">\r\n");
      out.write("                            <label for=\"2_area\">뚝섬 한강공원</label>\r\n");
      out.write("                            <input type='radio' name='crew_place' id=\"3_area\" value=\"반포한강공원\">\r\n");
      out.write("                            <label for=\"3_area\">반포 한강공원</label>\r\n");
      out.write("                            <input type='radio' name='crew_place' id=\"4_area\" value=\"여의도한강공원\">\r\n");
      out.write("                            <label for=\"4_area\">여의도 한강공원</label>\r\n");
      out.write("                            <input type='radio' name='crew_place' id=\"5_area\" value=\"난지한강공원\">\r\n");
      out.write("                            <label for=\"5_area\">난지 한강공원</label>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"apply-join\">4. 연락처<br><span class=\"apply-join-sub\">번호만 입력</span></li>\r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                            <input type=\"text\" id=\"crew_phone\" name=\"crew_phone\" placeholder=\"ex)01000000000\" class=\"apply-join-input\" required>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"apply-join\">5.이메일</li>\r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                            <input type=\"text\" id=\"crew_email\" name=\"crew_email\" class=\"apply-join-input\" required>\r\n");
      out.write("                            @\r\n");
      out.write("                            <input class=\"box\" id=\"domain-txt\" type=\"text\"/>\r\n");
      out.write("                            <select class=\"box\" id=\"domain-list\">\r\n");
      out.write("                                <option value=\"type\">직접 입력</option>\r\n");
      out.write("                                <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                                <option value=\"google.com\">google.com</option>\r\n");
      out.write("                                <option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("                                <option value=\"nate.com\">nate.com</option>\r\n");
      out.write("                                <option value=\"kakao.com\">kakao.com</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"plogging-check\" id=\"plogging-check\" class=\"apply-join-input-check\">\r\n");
      out.write("                            <label for=\"plogging-check\">개인정보 수집/ 이용 동의</label>\r\n");
      out.write("                            <br><br>\r\n");
      out.write("                            환경재단은 귀하의 개인정보를 매우 중요하게 여기며 『 개인정보보호법 』 에 따라 개인정보를 소중하게 관리하고 있습니다 .<br> 수집한 개인정보를 다음의 목적으로 수집 · 이용합니다 .1) 개인정보 수집 목적 : 쓰담한강 크루 선발과정 진행 및 환경재단 소식지 발송 <br>2) 개인정보 수집 항목 : 성명, 연락처 , 이메일, 생년월일, 소속  3) 이용기간 : 이용 목적이 다했거나 귀하가 이용 중단 의사를 밝힐 경우 파기함</label>\r\n");
      out.write("                        </li>                        \r\n");
      out.write("                        <li class=\"apply-join-input\">\r\n");
      out.write("                        	<input type=\"hidden\" id=\"member_no\" name=\"member_no\" value=\"");
if(m!=null){
      out.print(m.getMemberNo());
}
      out.write("\">\r\n");
      out.write("                        	<input type=\"hidden\" id=\"crew_kind\" name=\"crew_kind\" value=\"쓰담한강크루모집\">\r\n");
      out.write("                            <button type=\"submit\" class=\"button-submit\">제출</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer_wrap\">\r\n");
      out.write("        <div class=\"footer_text\">\r\n");
      out.write("            <p>재단법인 환경재단</p>\r\n");
      out.write("            <p>대표 진민호 대표전화 02-1111-1111 fax 02-111-1111</p>\r\n");
      out.write("            <p>문의 이메일 jinminho@kh.or.kr</p>\r\n");
      out.write("            <p>서울시 영등포구</p>\r\n");
      out.write("            <p>사업자 등록번호 111-11-11111</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침</a></li> \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- // footer -->");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<!-- script Line -->\r\n");
      out.write("    <script>\r\n");
      out.write("    //약관동의 로직\r\n");
      out.write("    function onchecked(){\r\n");
      out.write("        var ploggingCheck = $(\"input:checkbox[name='plogging-check']\").is(\":checked\");\r\n");
      out.write("\r\n");
      out.write("        if(!ploggingCheck){\r\n");
      out.write("            alert(\"약관에 동의해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //이메일 로직\r\n");
      out.write("    // 도메인 직접 입력 or domain option 선택\r\n");
      out.write("    const domainListEl = document.querySelector('#domain-list')\r\n");
      out.write("    const domainInputEl = document.querySelector('#domain-txt')\r\n");
      out.write("    // select 옵션 변경 시\r\n");
      out.write("    domainListEl.addEventListener('change', (event) => {\r\n");
      out.write("    // option에 있는 도메인 선택 시\r\n");
      out.write("    if(event.target.value !== \"type\") {\r\n");
      out.write("        // 선택한 도메인을 input에 입력하고 disabled\r\n");
      out.write("        domainInputEl.value = event.target.value\r\n");
      out.write("        domainInputEl.disabled = true\r\n");
      out.write("        $(\"input.box\").css('backgroundColor','#ced4da').css('border','1px solid black');\r\n");
      out.write("    } else { // 직접 입력 시\r\n");
      out.write("        // input 내용 초기화 & 입력 가능하도록 변경\r\n");
      out.write("        domainInputEl.value = \"\"\r\n");
      out.write("        domainInputEl.disabled = false\r\n");
      out.write("        $(\"input.box\").css('backgroundColor','white').css('border','1px solid black');\r\n");
      out.write("    }\r\n");
      out.write("    })\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
