/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-26 09:06:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.story;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.earthpurging.story.model.vo.Story;
import java.util.ArrayList;
import com.earthpurging.index.model.vo.ChellengeMemberData;
import com.earthpurging.member.model.vo.Member;

public final class storyList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1664172377681L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663920910595L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.earthpurging.index.model.vo.ChellengeMemberData");
    _jspx_imports_classes.add("com.earthpurging.member.model.vo.Member");
    _jspx_imports_classes.add("com.earthpurging.story.model.vo.Story");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	ArrayList<Story> list =(ArrayList<Story>)request.getAttribute("list");
  		String pageNavi = (String)request.getAttribute("pageNavi");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PHOTO STORY</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/PhotoStory.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	#pageNavi{\r\n");
      out.write("		margin: 30px;\r\n");
      out.write("		textalign : center;\r\n");
      out.write("	}\r\n");
      out.write("	.story-box{\r\n");
      out.write("    width: 320px;\r\n");
      out.write("    height : 460px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		Member m = (Member)session.getAttribute("m");
    
    	ChellengeMemberData cmd = (ChellengeMemberData)session.getAttribute("cmd"); 
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/default.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <div class=\"header-top\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/logo-plogging.png\" alt=\"plogging\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-center\">\r\n");
      out.write("                <a href=\"/\"><img src=\"/img/common/img-main-title.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-button\">\r\n");
      out.write("                <a href=\"\" >지구쓰담 후원하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-bottom\">\r\n");
      out.write("            <ul class=\"header-menu\">\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">줍깅 캠페인</a></li>\r\n");
      out.write("                <li><a href=\"/chellengeFrm.do?reqPage=1\">쓰담위크 퀘스트</a></li>\r\n");
      out.write("                <li><a href=\"/storyList.do?reqPage=1\">쓰담 스토리</a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\">쓰담 굿즈</a></li>\r\n");
      out.write("                <li><a href=\"/noticeList.do?reqPage=1\">쓰담 소식</a></li>\r\n");
      out.write("                <li><a href=\"/plogging.do\">진행중인 플로깅</a></li>\r\n");
      out.write("                ");
if(m!=null && m.getMemberLevel() == 1) {
      out.write("\r\n");
      out.write("                <li><a href=\"/admin.do\">관리자</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"util-menu\">\r\n");
      out.write("                ");
if(m!=null){
      out.write("\r\n");
      out.write("                <li><a href=\"/mypage.do\">");
      out.print(m.getNickname());
      out.write("</a></li>\r\n");
      out.write("                <li><a href=\"/logout.do\">로그아웃</a></li>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <li><a href=\"/common/signinFrm.jsp\">로그인/회원가입</a></li>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- // header -->");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"page-content\">\r\n");
      out.write("    	<div class=\"story-title\">\r\n");
      out.write("        	<h1>PHOTO STORY</h1>\r\n");
      out.write("            ");
 if(m!= null) {
      out.write("\r\n");
      out.write("            <div><a href=\"/storyWriteFrm.do\" class=\"btn bc3\">후기쓰기</a></div>\r\n");
      out.write("            ");
}else {
      out.write("\r\n");
      out.write("            <div><a href=\"/signinFrm.do\" class=\"btn bc3\">후기쓰기</a></div>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mid-content\">\r\n");
      out.write("            <div class=\"story-menu\">\r\n");
      out.write("            	<ul>\r\n");
      out.write("               		<li><a ref=\"storyList.do?reqPage=1\">PHOTO STORY</a></li>\r\n");
      out.write("                    <li><a ref=\"#\">COMMUNITY</a></li>\r\n");
      out.write("               	</ul>\r\n");
      out.write("           	</div> \r\n");
      out.write("            <div class=\"story-wrap\">\r\n");
      out.write("              	<div class=\"storylist\"> \r\n");
      out.write("              	");
for(Story s : list) { 
      out.write("\r\n");
      out.write("                	<div class=\"story-box\" data-idx=\"");
      out.print(s.getStoryNo());
      out.write("\">\r\n");
      out.write("                        <div class=\"photo-box\">\r\n");
      out.write("                       	<!--예시이미지-->\r\n");
      out.write("                       	\r\n");
      out.write("                        <a href=\"#상세페이지\"><img src=\"/upload/story/");
      out.print(s.getPhotoPath() );
      out.write("\"></a>\r\n");
      out.write("                   		</div>\r\n");
      out.write("                       	<div class=\"like-box\">\r\n");
      out.write("							<span id=\"storyWriter\">");
      out.print(s.getNickname() );
      out.write("</span>\r\n");
      out.write("                            <span class=\"material-symbols-outlined\">favorite</span>\r\n");
      out.write("                            </div> \r\n");
      out.write("                        <div class=\"story-text\">\r\n");
      out.write("                       		<a href=\"#상세페이지\"><span>");
      out.print(s.getStoryContent() );
      out.write("</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("						");
 if(m != null) {
      out.write(" \r\n");
      out.write("						    ");
 if(m.getMemberNo()== s.getStoryWriter()){ 
      out.write("                  \r\n");
      out.write("                        	<div class=\"pix-area\">\r\n");
      out.write("                            	<a href=\"/storyUpdateFrm.do?storyNo=");
      out.print(s.getStoryNo());
      out.write("\" class=\"btn bc2\">수정</a>\r\n");
      out.write("                            	<a href=\"/storyDelete.do?storyNo=");
      out.print( s.getStoryNo());
      out.write(" \"class=\"btn bc2\">삭제</a>\r\n");
      out.write("                        	</div> \r\n");
      out.write("                        	");
}else if(m.getMemberLevel() == 1) { 
      out.write("\r\n");
      out.write("                        	<div class=\"pix-area\">\r\n");
      out.write("                            	<a href=\"/storyDelete.do?storyNo=");
      out.print( s.getStoryNo());
      out.write(" \"class=\"btn bc2\">삭제</a>\r\n");
      out.write("                        	</div> \r\n");
      out.write("                        	");
}else {
      out.write("\r\n");
      out.write("                        		<div class=\"pix-area\" display=\"hidden\"></div>\r\n");
      out.write("                        	");
} 
      out.write("\r\n");
      out.write("                        ");
}else{ 
      out.write("\r\n");
      out.write("                        <div class=\"pix-area\" display=\"hidden\"></div>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                	</div>\r\n");
      out.write("      			");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("           	</div>\r\n");
      out.write("      	</div>\r\n");
      out.write("        <div id=\"pageNavi\">");
      out.print(pageNavi );
      out.write("</div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"story-modal\">\r\n");
      out.write("                <div class=\"modal-wrap\" style=\"margin-top:0\">\r\n");
      out.write("                    <div class=\"modal-top\">\r\n");
      out.write("                        <h1><span id=\"story-nickname\"></span>님의 PHOTO STORY</h1>\r\n");
      out.write("                        <span class=\"material-symbols-outlined\" id=\"modal-close\">close</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-mid\">\r\n");
      out.write("                        <div class=\"modal-photo\" id=\"modal-photo\">\r\n");
      out.write("                            <img id=\"story-img\" src=\"\"><br>\r\n");
      out.write("                            <span id=\"read-count\"></span>\r\n");
      out.write("                            <span id=\"reg-date\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-text\">\r\n");
      out.write("                            <span id=\"modal-text\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"story-comment\">\r\n");
      out.write("                        <ul class=\"posting-comment\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <p class=\"comment-info\">\r\n");
      out.write("                                    <span id=\"sc-writer\"></span>\r\n");
      out.write("                                    <span id=\"sc-date\"></span>\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"comment-content\"></p>                \r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
if(m!=null){ 
      out.write("\r\n");
      out.write("                    <div class=\"input-comment-box\">\r\n");
      out.write("                      	<ul>\r\n");
      out.write("                           <li>\r\n");
      out.write("                               	<input type=\"hidden\" name=\"scWriter\" id=\"hiddenWriter\"value=\"");
      out.print(m.getMemberNo());
      out.write("\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"storyRef\" id=\"storyRef\"value=\"\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"scRef\" id=\"hiddenScRef\" value=\"0\">");
      out.write("\r\n");
      out.write("                                <textarea class=\"input-form\" name=\"scContent\" id=\"hiddenScContent\"></textarea>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li>\r\n");
      out.write("                                <button type=\"button\" id=\"commentBtn\"class=\"btn bc5 bs4\">댓글달기</button>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>s\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer_wrap\">\r\n");
      out.write("        <div class=\"footer_text\">\r\n");
      out.write("            <p>재단법인 환경재단</p>\r\n");
      out.write("            <p>대표 진민호 대표전화 02-1111-1111 fax 02-111-1111</p>\r\n");
      out.write("            <p>문의 이메일 jinminho@kh.or.kr</p>\r\n");
      out.write("            <p>서울시 영등포구</p>\r\n");
      out.write("            <p>사업자 등록번호 111-11-11111</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침</a></li> \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- // footer -->");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	const nickname = $(\"#story-nickname\");\r\n");
      out.write("	const img = $(\"#story-img\");\r\n");
      out.write("	const storyContent = $(\"#modal-text\");\r\n");
      out.write("	const storyReadCount = $(\"#read-count\");\r\n");
      out.write("	const storyRegDate = $(\"#reg-date\");\r\n");
      out.write("	const storyRef = $(\"#storyRef\");\r\n");
      out.write("	const scWriter = $(\"#sc-writer\");\r\n");
      out.write("	const scDate = $(\"#sc-date\");\r\n");
      out.write("	const scContent = $(\".comment-content\");\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/*상세페이지 닫기*/ \r\n");
      out.write("	$(\"#modal-close\").on(\"click\",function(){\r\n");
      out.write("	    $(\".story-modal\").css(\"display\",\"none\");\r\n");
      out.write("	    nickname.empty();\r\n");
      out.write("	    img.attr(\"str\",\"\");\r\n");
      out.write("	    storyContent.empty();\r\n");
      out.write("	    storyReadCount.empty();\r\n");
      out.write("	    storyRegDate.empty();\r\n");
      out.write("	    storyRef.attr(\"value\",\"\");\r\n");
      out.write("	    scWriter.empty();\r\n");
      out.write("	    scDate.empty();\r\n");
      out.write("	    scContent.empty();\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	/*상세페이지 띄우기*/\r\n");
      out.write("	$(\".photo-box\").on(\"click\",function(){\r\n");
      out.write("	    $(\".story-modal\").css(\"display\",\"flex\");\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(\".story-box\").on(\"click\",function(){\r\n");
      out.write("		const storyIdx = $(this).attr(\"data-idx\");\r\n");
      out.write("		console.log(storyIdx);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"/storyView.do\",\r\n");
      out.write("			type: \"get\",\r\n");
      out.write("			data: {storyNo : storyIdx},\r\n");
      out.write("			//async : false,\r\n");
      out.write("			dataType : \"json\",//json타입인 것을 명시 2(servlet에서 명시하거나 jsp에서 명시)\r\n");
      out.write("			success: function(data){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				if(data == null){\r\n");
      out.write("					//.append(\"회원 정보를 조회할 수 없습니다.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					nickname.append(data.s.nickname);\r\n");
      out.write("					img.attr(\"src\",\"/upload/story/\"+data.s.photoPath);\r\n");
      out.write("					storyContent.append(data.s.storyContent);\r\n");
      out.write("					storyReadCount.append(\"조회수 : \"+data.s.storyReadCount);\r\n");
      out.write("					storyRegDate.append(data.s.storyRegDate);\r\n");
      out.write("					storyRef.attr(\"value\",data.s.storyNo);\r\n");
      out.write("					\r\n");
      out.write("					const storyComment = $(\".story-modal .story-comment\");\r\n");
      out.write("					storyComment.empty();\r\n");
      out.write("					\r\n");
      out.write("					for(let i=0;i<data.scList.length;i++){\r\n");
      out.write("						\r\n");
      out.write("						let html = '';\r\n");
      out.write("						\r\n");
      out.write("						html += '<ul class=\"posting-comment\">';\r\n");
      out.write("						html += '<li>';\r\n");
      out.write("                        html += '<p class=\"comment-info\">';\r\n");
      out.write("                        html += '   <span id=\"sc-writer\">' + data.scList[i].scNickname + '</span>';\r\n");
      out.write("                        html += '   <span id=\"sc-date\">'+ data.scList[i].scDate +'</span>';\r\n");
      out.write("                        html += '</p>';\r\n");
      out.write("                        html += '<p class=\"comment-content\">' + data.scList[i].scContent + '</p>';          \r\n");
      out.write("                    	html += '</li>';\r\n");
      out.write("                    	html += '</ul>';\r\n");
      out.write("                    	storyComment.append(html);\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					//result.append(\"이름 : \"+data.memberName+\"<br>\");\r\n");
      out.write("					//result.append(\"전화번호 : \"+data.memberPhone+\"<br>\");\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(){\r\n");
      out.write("				console.log(\"정보조회실패\");\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#commentBtn\").on(\"click\",function(){\r\n");
      out.write("		const scWriter = $(\"#hiddenWriter\").val();\r\n");
      out.write("		const scRef = $(\"#hiddenScRef\").val();\r\n");
      out.write("		const scContent = $(\"#hiddenScContent\").val();\r\n");
      out.write("		const storyRef = $(\"#storyRef\").val();\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"/insertStComment.do\",\r\n");
      out.write("			type: \"get\",\r\n");
      out.write("			data: {scWriter:scWriter, scRef:scRef, scContent:scContent, storyRef:storyRef},\r\n");
      out.write("			dataType: \"json\",\r\n");
      out.write("			//async:false,\r\n");
      out.write("			success: function(data){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				\r\n");
      out.write("				const storyComment = $(\".story-modal .story-comment\");\r\n");
      out.write("				storyComment.empty();\r\n");
      out.write("				\r\n");
      out.write("				if(data.length > 0) {\r\n");
      out.write("					for( let i=0; i<data.length;i++){\r\n");
      out.write("						let html = '';\r\n");
      out.write("						\r\n");
      out.write("						html += '<ul class=\"posting-comment\">';\r\n");
      out.write("						html += '<li>';\r\n");
      out.write("                        html += '<p class=\"comment-info\">';\r\n");
      out.write("                        html += '   <span id=\"sc-writer\">' + data[i].scNickname + '</span>';\r\n");
      out.write("                        html += '   <span id=\"sc-date\">'+ data[i].scDate +'</span>';\r\n");
      out.write("                        html += '</p>';\r\n");
      out.write("                        html += '<p class=\"comment-content\">' + data[i].scContent + '</p>';          \r\n");
      out.write("                    	html += '</li>';\r\n");
      out.write("                    	html += '</ul>';\r\n");
      out.write("                    	\r\n");
      out.write("                    	storyComment.append(html);\r\n");
      out.write("						\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("		\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
